{
  "hash": "1c0fdaae0c5c41612086432da3208b08",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Calibration of the asymptotic item-restscore test\"\nsubtitle: \"Null simulation of iarm::item_restscore() under a true Rasch model\"\nauthor: \"Magnus Johansson\"\ndate: 2026-10-04\ndate-modified: 2026-10-05\n---\n\n\n\n::: {.callout-note appearance=\"simple\" icon=false}\n## About this chapter\n\n**Status:** complete<br>\n**Computed with:** iarm 0.4.3, psychotools 0.7.6, R 4.6.1<br>\n**Cite as:** Johansson, M. (2026). Calibration of the asymptotic item-restscore\ntest. In *Rasch Measurement Explorations* (last modified October 5, 2026).\n<https://pgmj.github.io/rasch_book/chapters/restscore-asymptotic-null.html>\n:::\n\n::: {.callout-tip appearance=\"simple\" icon=false}\n## Summary\n\nThe item-restscore test in `iarm::item_restscore()` compares observed and\nexpected Goodman-Kruskal gamma and refers the difference to a standard normal.\nUnder a true Rasch model it is not calibrated. The standard error is right for\nthe observed gamma, but the expected gamma is estimated from the same data and\nmoves with it, so $z$ is too small by a nearly constant factor. A small-sample\nbias also pushes $z$ upward. The underfit tail rejects 0.2% to 1.2% against a\nnominal 2.5%. Family-wise, with BH over the items, a true Rasch model gets at\nleast one flagged item in 13.5% of dichotomous samples at n = 150 (30.5% when\nmistargeted), while polytomous data are conservative at every n. A parametric\nbootstrap that re-estimates the thresholds in every replication would absorb\nboth distortions.\n:::\n\n## Purpose {#sec-rs-purpose}\n\n`RMitemRestscore()` flags items using the p-value from `iarm::item_restscore()`.\nThe test statistic is\n\n$$\nz_i = \\frac{\\hat\\gamma_i^{\\text{obs}} - \\hat\\gamma_i^{\\text{exp}}}{\\text{ASE}(\\hat\\gamma_i^{\\text{obs}})},\n$$\n\nreferred to the standard normal, two-sided, then adjusted over the $k$ items\n(BH by default). The observed gamma is Goodman-Kruskal gamma for the\nitem × restscore table. The expected gamma is computed from the CML item\nparameters and the observed score distribution. The ASE is the delta-method\nstandard error that `vcdExtra::GKgamma()` returns for the observed table.\n\nTwo features of this construction give reasons to check calibration directly\ninstead of assuming it:\n\n1. **The expected gamma is treated as known.** It is a function of estimated\n   thresholds, and it is estimated from the same data as the observed gamma.\n   The ASE ignores both the estimation uncertainty and the correlation between\n   the two terms. The sign of the resulting bias cannot be worked out without\n   simulating it.\n2. **The ASE is the delta-method SE computed under the alternative.** van der\n   Ark and van Aert [-@vanderark2015] found it had the worst coverage of four CI types for\n   bivariate gamma, but only for tables up to 5 × 5 at N ≤ 100 [@vanderark2015]. The\n   item × restscore table is larger (4 × 28 for nine four-category items), with\n   sparse cells in the tails of the restscore.\n\nThe partial gamma LD and DIF functions already have simulation-based cutoffs.\nItem-restscore does not. `RMitemRestscoreBoot()` resamples the data and counts\nhow often each item is flagged, which describes stability and not calibration.\n\nAn earlier simulation hinted at this. It reported item-restscore as well\ncalibrated from per-item false positive rates, but counted as the share of\nreplications with at least one BH-flagged item, its small-sample rate was above\n5 percent. That study is not reported here, so this is the motivation for the\ncheck, not evidence.\n\n## Design {#sec-rs-design}\n\n- **Item sets.** (a) 20 dichotomous items with locations evenly spaced on\n  [-2, 2], as in the S-X2 comparison (@sec-sx2-comp-design). (b) 9 polytomous items with four categories,\n  locations evenly spaced on [-1.5, 1.5], and thresholds at location ± 1.2 and\n  location + 0, as a PHQ-9-sized scale.\n- **Persons.** θ ~ N(μ, 1.5²), with μ = 0 (targeted) or μ = 1.5 (mistargeted),\n  since sparse restscore tails are a plausible source of miscalibration.\n- **Sample sizes.** 150, 300, 600, 1000, 2000.\n- **Replications.** 4000 per cell. The Monte Carlo SE of a 5 percent rate is\n  then 0.34 points.\n- **Fitting.** Same as the package: `psychotools::pcmodel()`, then\n  `iarm::item_restscore()`. A replication with an unobserved category (or an\n  item with zero variance) is discarded and counted, since the package would\n  not fit it either.\n\n`iarm` returns its results rounded to four decimals, so $z$ is recomputed from\nthe rounded observed, expected and SE columns and the p-values from $z$. With SEs\naround .02 to .05 the rounding moves $z$ by at most about .003.\n\nFor each item and replication the observed gamma, expected gamma and ASE are\nstored. Calibration is summarised in three ways.\n\n- Per-item rejection at two-sided α = .05, and separately in each tail at .025.\n- Family-wise rejection (any item flagged) with no adjustment, BH as in the\n  package default, and Bonferroni.\n- A decomposition of the SE. If the ASE were correct for the test statistic,\n  the empirical SD of $\\hat\\gamma^{\\text{obs}} - \\hat\\gamma^{\\text{exp}}$ across\n  replications would equal the root mean squared ASE. The ratio\n  $\\text{SD}(\\hat\\gamma^{\\text{obs}}) / \\text{RMS(ASE)}$ checks the ASE as an SE\n  for the observed gamma alone. Comparing the two ratios separates point 1 from\n  point 2 in @sec-rs-purpose.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsuppressMessages({\n  library(psychotools)\n  library(iarm)\n  library(parallel)\n  library(dplyr)\n  library(tidyr)\n  library(ggplot2)\n})\noptions(rgl.useNULL = TRUE)\n\nR_REPS   <- 4000\nNS       <- c(150, 300, 600, 1000, 2000)\nMUS      <- c(0, 1.5)\nTHETA_SD <- 1.5\nNCORES   <- 10\nRES_FILE <- \"results/restscore/restscore_asymptotic_null.rds\"\n```\n:::\n\n\n### Item parameters\n\n\n::: {.cell}\n\n```{.r .cell-code}\nitem_sets <- list(\n  dich = as.list(seq(-2, 2, length.out = 20)),\n  poly = lapply(seq(-1.5, 1.5, length.out = 9), function(l) l + c(-1.2, 0, 1.2))\n)\n\ndata.frame(\n  set = c(\"dich\", \"poly\"),\n  items = lengths(item_sets),\n  categories = c(2, 4),\n  location_range = c(\"-2 to 2\", \"-1.5 to 1.5\")\n)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|     |set  | items| categories|location_range |\n|:----|:----|-----:|----------:|:--------------|\n|dich |dich |    20|          2|-2 to 2        |\n|poly |poly |     9|          4|-1.5 to 1.5    |\n\n</div>\n:::\n:::\n\n\n### Data generation\n\nPartial credit model, vectorised over persons. `thr` is one threshold vector per\nitem. A dichotomous item is a PCM item with one threshold.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsim_pcm <- function(theta, thr) {\n  n <- length(theta)\n  sapply(thr, function(d) {\n    m <- length(d)\n    eta <- outer(theta, 0:m) -\n      matrix(c(0, cumsum(d)), n, m + 1, byrow = TRUE)\n    p <- exp(eta - apply(eta, 1, max))\n    p <- p / rowSums(p)\n    cp <- p %*% upper.tri(diag(m + 1), diag = TRUE)\n    rowSums(runif(n) > cp)\n  })\n}\n```\n:::\n\n\n### One replication\n\n\n::: {.cell}\n\n```{.r .cell-code}\none_rep <- function(rep, set, n, mu) {\n  set.seed(1e7 * match(set, names(item_sets)) + 1e5 * match(mu, MUS) +\n             10 * n + rep)\n  thr <- item_sets[[set]]\n  d <- as.data.frame(sim_pcm(rnorm(n, mu, THETA_SD), thr))\n  names(d) <- paste0(\"I\", seq_along(thr))\n\n  # every category observed in every item, as the CML fit requires\n  full <- all(mapply(function(x, m) all(tabulate(x + 1, m + 1) > 0),\n                     d, lengths(thr)))\n  if (!full) return(NULL)\n\n  res <- tryCatch({\n    fit <- psychotools::pcmodel(d, hessian = FALSE)\n    r <- iarm::item_restscore(fit, p.adj = \"none\")\n    matrix(as.numeric(r[seq_along(thr), c(\"observed\", \"expected\", \"se\")]),\n           ncol = 3, dimnames = list(NULL, c(\"obs\", \"exp\", \"se\")))\n  }, error = function(e) NULL)\n  res\n}\n```\n:::\n\n\n### Run\n\nResults are cached. Delete results/restscore/restscore_asymptotic_null.rds to force a re-run.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngrid <- expand.grid(rep = seq_len(R_REPS), n = NS, mu = MUS,\n                    set = names(item_sets), stringsAsFactors = FALSE)\n\nif (file.exists(RES_FILE)) {\n  sim <- readRDS(RES_FILE)\n} else {\n  t0 <- Sys.time()\n  res <- mclapply(seq_len(nrow(grid)),\n                  function(i) one_rep(grid$rep[i], grid$set[i],\n                                      grid$n[i], grid$mu[i]),\n                  mc.cores = NCORES, mc.preschedule = TRUE)\n  sim <- list(res = res, grid = grid, item_sets = item_sets,\n              elapsed_min = as.numeric(Sys.time() - t0, units = \"mins\"))\n  saveRDS(sim, RES_FILE)\n}\ncat(\"elapsed:\", round(sim$elapsed_min, 1), \"min\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nelapsed: 9.9 min\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nok <- !vapply(sim$res, is.null, logical(1))\n\nsim$grid |>\n  mutate(ok = ok) |>\n  group_by(set, mu, n) |>\n  summarise(discarded = sum(!ok), .groups = \"drop\") |>\n  filter(discarded > 0)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|set  |  mu|   n| discarded|\n|:----|---:|---:|---------:|\n|poly | 0.0| 150|         1|\n|poly | 1.5| 150|      1126|\n|poly | 1.5| 300|       224|\n|poly | 1.5| 600|         8|\n\n</div>\n:::\n\n```{.r .cell-code}\nitem_loc <- lapply(sim$item_sets, function(s) vapply(s, mean, numeric(1)))\n\nlong <- do.call(rbind, lapply(which(ok), function(i) {\n  g <- sim$grid[i, ]\n  m <- sim$res[[i]]\n  data.frame(set = g$set, mu = g$mu, n = g$n, rep = g$rep,\n             item = seq_len(nrow(m)),\n             location = item_loc[[g$set]], m)\n})) |>\n  mutate(diff = obs - exp,\n         z = diff / se,\n         p = 2 * pnorm(-abs(z)))\n```\n:::\n\n\n## Results {#sec-rs-results}\n\n### Per-item rejection rates\n\nNominal 5.0 percent two-sided, 2.5 percent in each tail. `over` is observed\ngamma above expected (the package labels this overfit), `under` is below.\n\nAn observed gamma of exactly ±1 has an ASE of zero, which gives an infinite $z$\nand p = 0. The package flags such an item, so it counts as a rejection here, but\nit is left out of the mean and SD of $z$. `se_zero` counts these cases.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlong |>\n  group_by(set, mu, n) |>\n  summarise(two_sided = 100 * mean(p < .05),\n            over = 100 * mean(z > qnorm(.975)),\n            under = 100 * mean(z < qnorm(.025)),\n            mean_z = mean(z[is.finite(z)]),\n            sd_z = sd(z[is.finite(z)]),\n            se_zero = sum(se == 0),\n            .groups = \"drop\") |>\n  mutate(across(two_sided:under, \\(x) round(x, 2)),\n         across(c(mean_z, sd_z), \\(x) round(x, 3)))\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|set  |  mu|    n| two_sided| over| under| mean_z|  sd_z| se_zero|\n|:----|---:|----:|---------:|----:|-----:|------:|-----:|-------:|\n|dich | 0.0|  150|      4.74| 4.11|  0.64|  0.153| 0.970|       0|\n|dich | 0.0|  300|      3.78| 2.99|  0.79|  0.104| 0.932|       0|\n|dich | 0.0|  600|      3.56| 2.58|  0.98|  0.072| 0.921|       0|\n|dich | 0.0| 1000|      3.36| 2.34|  1.02|  0.057| 0.921|       0|\n|dich | 0.0| 2000|      3.08| 1.94|  1.15|  0.039| 0.907|       0|\n|dich | 1.5|  150|      6.29| 5.66|  0.63|  0.212| 1.135|       2|\n|dich | 1.5|  300|      4.71| 4.01|  0.70|  0.130| 0.981|       0|\n|dich | 1.5|  600|      3.94| 3.08|  0.86|  0.089| 0.942|       0|\n|dich | 1.5| 1000|      3.76| 2.70|  1.06|  0.067| 0.934|       0|\n|dich | 1.5| 2000|      3.37| 2.27|  1.09|  0.046| 0.922|       0|\n|poly | 0.0|  150|      2.94| 2.67|  0.27|  0.149| 0.862|       0|\n|poly | 0.0|  300|      2.40| 1.98|  0.42|  0.106| 0.842|       0|\n|poly | 0.0|  600|      2.03| 1.59|  0.44|  0.073| 0.837|       0|\n|poly | 0.0| 1000|      1.89| 1.35|  0.54|  0.057| 0.833|       0|\n|poly | 0.0| 2000|      1.89| 1.24|  0.65|  0.040| 0.831|       0|\n|poly | 1.5|  150|      3.16| 2.92|  0.24|  0.152| 0.874|       0|\n|poly | 1.5|  300|      2.59| 2.23|  0.36|  0.106| 0.856|       0|\n|poly | 1.5|  600|      2.07| 1.62|  0.44|  0.072| 0.835|       0|\n|poly | 1.5| 1000|      2.14| 1.61|  0.52|  0.058| 0.838|       0|\n|poly | 1.5| 2000|      2.04| 1.36|  0.68|  0.041| 0.840|       0|\n\n</div>\n:::\n:::\n\n\n### Family-wise rejection\n\nProportion of replications with at least one flagged item. Under a complete\nnull, BH and Bonferroni both control this at 5 percent. The unadjusted column\nshows what the per-item test implies across 9 or 20 items.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfw <- long |>\n  group_by(set, mu, n, rep) |>\n  summarise(none = any(p < .05),\n            bh = any(p.adjust(p, \"BH\") < .05),\n            bonferroni = any(p.adjust(p, \"bonferroni\") < .05),\n            .groups = \"drop\") |>\n  group_by(set, mu, n) |>\n  summarise(reps = n(),\n            across(c(none, bh, bonferroni), \\(x) round(100 * mean(x), 2)),\n            .groups = \"drop\")\nfw\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|set  |  mu|    n| reps|  none|    bh| bonferroni|\n|:----|---:|----:|----:|-----:|-----:|----------:|\n|dich | 0.0|  150| 4000| 63.38| 13.45|      13.38|\n|dich | 0.0|  300| 4000| 54.93|  6.20|       6.15|\n|dich | 0.0|  600| 4000| 51.95|  4.05|       4.03|\n|dich | 0.0| 1000| 4000| 49.30|  2.72|       2.67|\n|dich | 0.0| 2000| 4000| 45.80|  2.30|       2.28|\n|dich | 1.5|  150| 4000| 73.78| 30.50|      30.18|\n|dich | 1.5|  300| 4000| 63.05| 13.88|      13.80|\n|dich | 1.5|  600| 4000| 56.03|  7.38|       7.32|\n|dich | 1.5| 1000| 4000| 53.12|  4.85|       4.82|\n|dich | 1.5| 2000| 4000| 49.33|  3.22|       3.15|\n|poly | 0.0|  150| 3999| 24.08|  4.23|       4.18|\n|poly | 0.0|  300| 4000| 19.68|  2.17|       2.17|\n|poly | 0.0|  600| 4000| 16.92|  1.80|       1.77|\n|poly | 0.0| 1000| 4000| 15.40|  0.92|       0.92|\n|poly | 0.0| 2000| 4000| 15.68|  1.10|       1.10|\n|poly | 1.5|  150| 2874| 25.96|  5.11|       5.08|\n|poly | 1.5|  300| 3776| 21.00|  3.02|       2.99|\n|poly | 1.5|  600| 3992| 17.16|  1.65|       1.65|\n|poly | 1.5| 1000| 4000| 17.50|  1.18|       1.12|\n|poly | 1.5| 2000| 4000| 16.83|  1.60|       1.60|\n\n</div>\n:::\n:::\n\n\n### Where the SE goes wrong\n\n`sd_diff / rms_se` near 1 means the ASE is the right SE for the test statistic.\n`sd_obs / rms_se` near 1 means it is the right SE for the observed gamma alone.\n`cor_obs_exp` is the correlation between observed and expected gamma across\nreplications, averaged over items.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nse_tab <- long |>\n  group_by(set, mu, n, item) |>\n  summarise(sd_diff = sd(diff), sd_obs = sd(obs), sd_exp = sd(exp),\n            rms_se = sqrt(mean(se^2)), cor_obs_exp = cor(obs, exp),\n            .groups = \"drop\") |>\n  group_by(set, mu, n) |>\n  summarise(sd_diff_over_rms_se = mean(sd_diff / rms_se),\n            sd_obs_over_rms_se = mean(sd_obs / rms_se),\n            sd_exp_over_rms_se = mean(sd_exp / rms_se),\n            cor_obs_exp = mean(cor_obs_exp),\n            .groups = \"drop\") |>\n  mutate(across(where(is.double) & !c(mu), \\(x) round(x, 3)))\nse_tab\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|set  |  mu|    n| sd_diff_over_rms_se| sd_obs_over_rms_se| sd_exp_over_rms_se| cor_obs_exp|\n|:----|---:|----:|-------------------:|------------------:|------------------:|-----------:|\n|dich | 0.0|  150|               0.914|              1.008|              0.428|       0.422|\n|dich | 0.0|  300|               0.907|              1.000|              0.421|       0.421|\n|dich | 0.0|  600|               0.909|              1.001|              0.420|       0.419|\n|dich | 0.0| 1000|               0.913|              1.003|              0.413|       0.412|\n|dich | 0.0| 2000|               0.904|              1.000|              0.428|       0.428|\n|dich | 1.5|  150|               0.926|              1.012|              0.407|       0.401|\n|dich | 1.5|  300|               0.919|              1.004|              0.401|       0.398|\n|dich | 1.5|  600|               0.915|              1.001|              0.402|       0.402|\n|dich | 1.5| 1000|               0.919|              1.007|              0.407|       0.406|\n|dich | 1.5| 2000|               0.915|              0.998|              0.396|       0.396|\n|poly | 0.0|  150|               0.830|              1.000|              0.563|       0.558|\n|poly | 0.0|  300|               0.827|              1.005|              0.571|       0.568|\n|poly | 0.0|  600|               0.828|              0.996|              0.554|       0.556|\n|poly | 0.0| 1000|               0.828|              0.997|              0.559|       0.556|\n|poly | 0.0| 2000|               0.829|              0.999|              0.559|       0.557|\n|poly | 1.5|  150|               0.829|              0.999|              0.553|       0.555|\n|poly | 1.5|  300|               0.834|              0.997|              0.545|       0.547|\n|poly | 1.5|  600|               0.825|              0.988|              0.541|       0.550|\n|poly | 1.5| 1000|               0.831|              0.998|              0.552|       0.551|\n|poly | 1.5| 2000|               0.836|              1.002|              0.547|       0.549|\n\n</div>\n:::\n:::\n\n\n### Per-item rates by item location\n\nIf sparse restscore tails matter, items far from the sample mean should be the\nworst calibrated, and more so under mistargeting.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlong |>\n  group_by(set, mu, n, item, location) |>\n  summarise(rate = 100 * mean(p < .05), .groups = \"drop\") |>\n  mutate(rel_location = location - mu,\n         mu = paste(\"μ =\", mu)) |>\n  ggplot(aes(rel_location, rate, colour = factor(n))) +\n  geom_hline(yintercept = 5, linetype = \"dashed\", colour = \"grey40\") +\n  geom_line() +\n  geom_point(size = 1) +\n  facet_grid(set ~ mu, scales = \"free_x\") +\n  labs(x = \"Item location relative to person mean (logits)\",\n       y = \"Per-item rejection rate (%)\", colour = \"n\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](restscore-asymptotic-null_files/figure-html/byitem-1.png)\n:::\n:::\n\n\n### Distribution of z\n\nQuantile plot against the standard normal, pooled over items, for the smallest\nand largest n. Points on the diagonal mean the reference distribution is right.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlong |>\n  filter(n %in% range(NS)) |>\n  group_by(set, mu, n) |>\n  mutate(theoretical = qnorm(ppoints(n()))[rank(z, ties.method = \"first\")]) |>\n  slice_sample(n = 5000) |>\n  ungroup() |>\n  mutate(cell = paste0(set, \", μ = \", mu)) |>\n  ggplot(aes(theoretical, z, colour = factor(n))) +\n  geom_abline(linetype = \"dashed\", colour = \"grey40\") +\n  geom_point(size = 0.4, alpha = 0.4) +\n  facet_wrap(~cell) +\n  coord_equal() +\n  labs(x = \"N(0, 1) quantile\", y = \"Observed z\", colour = \"n\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](restscore-asymptotic-null_files/figure-html/qq-1.png)\n:::\n:::\n\n\n## Interpretation {#sec-rs-interpretation}\n\nThe asymptotic item-restscore test is not calibrated. Two separate distortions\nact on it, and neither vanishes as n grows.\n\n**1. The ASE is right for the observed gamma but wrong for the test statistic.**\nThe SD of the observed gamma across replications matches the root mean squared\nASE to within 1 percent in every cell, so the delta-method SE is not the\nproblem. The problem is that the expected gamma varies across samples and moves\nwith the observed gamma (correlation about .41 for the dichotomous set and .55\nfor the polytomous set). Its variance roughly equals the covariance, so the\ndifference varies less than the observed gamma alone. The SD of the difference\nis 0.91 times the ASE for dichotomous items and 0.83 times for polytomous items,\nnearly constant across sample size and targeting. Dividing by the ASE therefore\nshrinks $z$ by a fixed factor, and the test is conservative at every sample\nsize. This is point 1 from @sec-rs-purpose, and point 2 does not show up at\nall.\n\n**2. A small-sample bias pushes $z$ upwards.** Mean $z$ is .15 at n = 150 and\nfalls to .04 at n = 2000, roughly in proportion to $1/\\sqrt{n}$. This is what a\nbias of order $1/n$ in the gamma difference produces. It inflates the upper tail\n(observed gamma above expected, labelled overfit by the package) and depletes\nthe lower tail. It is largest for items far from the person mean, reaching\n14 percent two-sided at n = 150 for the easiest dichotomous item under\nmistargeting.\n\n**Net effect on single items.** Nominal is 5 percent two-sided. Dichotomous\nitems reject 4.7 percent at n = 150 when targeted, falling to 3.1 at n = 2000.\nPolytomous items reject 2.9 falling to 1.9. The tails are lopsided. The lower\ntail, which is the underfit direction and the usual signature of\nmultidimensionality, rejects 0.2 to 1.2 percent against a nominal 2.5 in every\ncell, a tenth to a half of what it should. The upper tail exceeds 2.5 percent at\nsmall n for dichotomous items. The power cost of the deflated lower tail is not\nmeasured here, but it follows directly: underfit has to be larger than the\nnominal level implies before it is flagged.\n\n**Family-wise rates, which is what a user sees.** With BH over the items, the\nprobability that a true Rasch model gets at least one item flagged is:\n\n- dichotomous, targeted: 13.5, 6.2, 4.1, 2.7 and 2.3 percent at n = 150 to 2000\n- dichotomous, mistargeted: 30.5, 13.9, 7.4, 4.9 and 3.2 percent\n- polytomous, targeted: 4.2 falling to 0.9 to 1.1 percent\n- polytomous, mistargeted: 5.1 falling to 1.2 to 1.6 percent\n\nSo the same test is liberal for dichotomous data at small n,\nespecially when mistargeted, and conservative for polytomous data at every n.\nNo single correction to the nominal level fixes both.\nBH and Bonferroni give nearly identical rates, as expected under a complete\nnull.\n\n**Discarded replications.** 28 percent of the mistargeted polytomous\nreplications at n = 150 and 6 percent at n = 300 had an unobserved category and\nwere discarded. Those two cells describe samples where every category is used,\nwhich are also the only samples the package can fit.\n\n**For easyRasch2.** Both distortions come from treating the expected gamma as a\nfixed reference, and both depend on the item set, sample size and targeting. A\nparametric bootstrap that simulates from the fitted model, **re-estimates the\nthresholds in every replication**, and recomputes the observed minus expected\ndifference would absorb both, in the same way as `RMitemInfitCutoff()`. A\nbootstrap that holds the thresholds fixed would reproduce distortion 1. The\nitem-restscore statistic is cheap (about 0.1 s per replication including the\nCML fit), so an `RMitemRestscoreCutoff()` at the same iteration counts as the\ninfit cutoffs is affordable. This simulation says nothing about power. That\ncomparison, against infit with simulation-based cutoffs, is the natural next\nstep.\n\n## Revision history {.unnumbered}\n\n- 2026-10-04: first version in this book, moved from `easyRasch2/dev/restscore_asymptotic_null.qmd`.\n- 2026-10-05: removed false positive rates quoted from an earlier S-X2 simulation, which has been withdrawn. The motivation is kept as one paragraph. No result of this chapter changed.\n",
    "supporting": [
      "restscore-asymptotic-null_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}