{
  "hash": "b4bf0a7da655a956f75220af4d8b9348",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Generalized S-X2 compared to conditional infit and item-restscore\"\nsubtitle: \"Detection of 1-3 misfitting items under multidimensionality\"\nauthor: \"Magnus Johansson\"\ndate: 2026-10-04\ndate-modified: 2026-10-04\n---\n\n\n\n::: {.callout-note appearance=\"simple\" icon=false}\n## About this chapter\n\n**Status:** complete. Conclusion 3 is corrected in @sec-sx2-familywise.<br>\n**Simulated:** 2026-07-27 with easyRasch2 1.1.0. Tables are rendered from the\ncached results with mirt 1.46.1, eRm 1.0.10, R 4.6.1.<br>\n**Cite as:** Johansson, M. (2026). Generalized S-X2 compared to conditional\ninfit and item-restscore. In *Rasch Measurement Explorations*.\n<https://pgmj.github.io/rasch_book/chapters/sx2-itemfit.html>\n:::\n\n::: {.callout-tip appearance=\"simple\" icon=false}\n## Summary\n\nThe generalized S-X2 index was compared with conditional infit and\nitem-restscore on the same simulated datasets, with 1 to 3 items misfitting\nthrough multidimensionality among 20 dichotomous items. S-X2 has no power\nadvantage, and against subtle misfit it detects clearly less than conditional\ninfit. Its contribution is under strong misfit at large n, where it produces far\nfewer false flags on fitting items than the other two methods. A fixed\nRMSEA.S_X2 threshold of .05 is not usable in either direction. Under a true\nRasch model, none of the methods holds a 5% family-wise rate, and uncorrected\nS-X2 p-values reject 7% to 9% per item.\n:::\n\n## Purpose {#sec-sx2-purpose}\n\n@johansson2025 compared conditional item infit (with simulation-based cutoffs)\nand item-restscore for detecting item misfit caused by multidimensionality, and\nfound that neither method behaves well at large sample sizes: false positive\nrates rise sharply from n = 1000 onwards. @kang2008 report that the\ngeneralized S-X2 index maintains nominal Type I error rates from n = 500 up to\nn = 5000, which raises the question of whether it could fill that gap.\n\nTwo things make this worth testing rather than assuming:\n\n1. Kang and Chen only evaluated power in conditions where **every** item was\n   misfitting, and where misfit was a clean nested-model contrast (RSM data\n   calibrated as PCM, etc.). The realistic case of a few misfitting items among\n   fitting ones was explicitly left for future work.\n2. The follow-up study on the graded response model [@kang2011] found S-X2\n   power to be \"much lower when the source of misfit was multidimensionality\"\n   than when it came from a wrong item response function. Multidimensionality is precisely\n   the misfit source used in @johansson2025, and the dominant concern in\n   applied Rasch analysis.\n\nThis simulation therefore replicates the @johansson2025 design and adds\nS-X2 as a fourth method, so all methods are evaluated on the *same* datasets.\n\n## Design {#sec-sx2-design}\n\nFollowing @johansson2025:\n\n- 20 dichotomous items, locations drawn from `runif(20, -2, 2)`\n- person locations from a bivariate normal, SD 1.5, correlation 0.15 between\n  dimensions (lower correlation = stronger multidimensionality)\n- misfit induced with `eRm::sim.xdim()` by loading selected items on the second\n  dimension\n- misfitting items chosen at approximately 0, -1 and -2 logits relative to the\n  sample mean, to vary targeting\n- master datasets of 10 000 respondents, from which samples are drawn\n- sample sizes 150, 250, 500, 1000, 2000\n\nThree misfit conditions are used: **0** misfitting items (a clean null, to\nmeasure Type I error uncontaminated by other misfitting items), **1**\n(the on-target item only), and **3**.\n\nFour decision rules are compared:\n\n| Label | Rule |\n|---|---|\n| `infit` | conditional infit MSQ outside simulation-based cutoffs (`RMitemInfitCutoff`, 100 iterations for n < 500, 200 otherwise) |\n| `restscore` | item-restscore gamma, BH-corrected p < .05 |\n| `sx2_bh` | generalized S-X2, BH-corrected p < .05 |\n| `sx2_rmsea` | RMSEA.S_X2 > .05 (effect size, no significance test) |\n\nUncorrected S-X2 p-values are also recorded, since infit cutoffs are not\nmultiplicity-corrected and the comparison should be readable either way.\n\nS-X2 is computed via `mirt::itemfit()`, which implements the Kang and Chen\ngeneralization. Note that this estimates item parameters by MML under a normal\nθ prior, whereas the other two methods use CML — see the discussion at the end.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsuppressMessages({\n  library(mirt)\n  library(easyRasch2)\n  library(eRm)\n  library(MASS)\n  library(parallel)\n  library(dplyr)\n  library(tidyr)\n  library(ggplot2)\n})\n\nR_REPS   <- 200\nNS       <- c(150, 250, 500, 1000, 2000)\nNMISFITS <- c(0, 1, 3)\nNCORES   <- 10\nRES_FILE <- \"results/sx2/sx2_itemfit_sim_results.rds\"\n```\n:::\n\n\n### Data generation\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmake_master <- function(n_misfit, N = 10000, seed = 20250727) {\n  set.seed(seed)\n  locs <- runif(20, -2, 2)\n  # items closest to 0, -1, -2 logits (sample theta mean = 0)\n  misfit_idx <- integer(0)\n  for (tg in c(0, -1, -2)) {\n    cand <- setdiff(order(abs(locs - tg)), misfit_idx)[1]\n    misfit_idx <- c(misfit_idx, cand)\n  }\n  use <- misfit_idx[seq_len(n_misfit)]\n  W <- cbind(rep(1, 20), rep(0, 20))\n  if (n_misfit > 0) W[use, ] <- matrix(c(0, 1), nrow = length(use), ncol = 2,\n                                       byrow = TRUE)\n  Sigma <- matrix(c(1.5^2, .15 * 1.5^2, .15 * 1.5^2, 1.5^2), 2, 2)\n  set.seed(seed + n_misfit)\n  th <- MASS::mvrnorm(N, mu = c(0, 0), Sigma = Sigma)\n  d <- as.data.frame(eRm::sim.xdim(persons = th, items = locs,\n                                   Sigma = Sigma, weightmat = W))\n  names(d) <- paste0(\"V\", 1:20)\n  list(data = d, locs = locs, misfit = use, misfit_all = misfit_idx)\n}\n\nmasters <- lapply(NMISFITS, make_master)\nnames(masters) <- as.character(NMISFITS)\nmisfit_all <- masters[[\"3\"]]$misfit\nlocs <- masters[[\"3\"]]$locs\n\ndata.frame(\n  item = paste0(\"V\", misfit_all),\n  intended_location = c(0, -1, -2),\n  actual_location = round(locs[misfit_all], 2)\n)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|item | intended_location| actual_location|\n|:----|-----------------:|---------------:|\n|V8   |                 0|            0.04|\n|V12  |                -1|           -1.00|\n|V11  |                -2|           -2.00|\n\n</div>\n:::\n:::\n\n\n### One replication\n\n\n::: {.cell}\n\n```{.r .cell-code}\none_rep <- function(rep, k, n) {\n  set.seed(1e6 * k + 1e3 * n + rep)\n  md <- masters[[as.character(k)]]$data\n  d  <- md[sample(nrow(md), n), ]\n  iters <- if (n < 500) 100 else 200\n  out <- matrix(NA_integer_, nrow = 20, ncol = 5,\n                dimnames = list(NULL, c(\"infit\", \"restscore\", \"sx2_raw\",\n                                        \"sx2_bh\", \"sx2_rmsea\")))\n  try({\n    co <- RMitemInfitCutoff(d, iterations = iters, parallel = FALSE,\n                            seed = rep, verbose = FALSE)\n    fi <- RMitemInfit(d, cutoff = co, output = \"dataframe\")\n    out[, \"infit\"] <- as.integer(fi$Flagged[match(names(d), fi$Item)] != \"\")\n  }, silent = TRUE)\n  try({\n    rs <- RMitemRestscore(d, output = \"dataframe\", p_adj = \"BH\")\n    out[, \"restscore\"] <- as.integer(rs$Flagged[match(names(d), rs$Item)] != \"\")\n  }, silent = TRUE)\n  try({\n    mm <- mirt(d, 1, itemtype = \"Rasch\", verbose = FALSE)\n    f  <- mirt::itemfit(mm, fit_stats = \"S_X2\")\n    i  <- match(names(d), f$item)\n    out[, \"sx2_raw\"]   <- as.integer(f$p.S_X2[i] < .05)\n    out[, \"sx2_bh\"]    <- as.integer(p.adjust(f$p.S_X2, \"BH\")[i] < .05)\n    out[, \"sx2_rmsea\"] <- as.integer(f$RMSEA.S_X2[i] > .05)\n  }, silent = TRUE)\n  out\n}\n```\n:::\n\n\n### Run\n\nResults are cached; delete results/sx2/sx2_itemfit_sim_results.rds to force a re-run.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngrid <- expand.grid(rep = 1:R_REPS, n = NS, k = NMISFITS)\n\nif (file.exists(RES_FILE)) {\n  sim <- readRDS(RES_FILE)\n} else {\n  t0 <- Sys.time()\n  res <- mclapply(seq_len(nrow(grid)),\n                  function(i) one_rep(grid$rep[i], grid$k[i], grid$n[i]),\n                  mc.cores = NCORES)\n  sim <- list(res = res, grid = grid, misfit = misfit_all, locs = locs,\n              elapsed_min = as.numeric(Sys.time() - t0, \"mins\"))\n  saveRDS(sim, RES_FILE)\n}\n\nlong <- do.call(rbind, lapply(seq_len(nrow(sim$grid)), function(i) {\n  m <- sim$res[[i]]\n  data.frame(k = sim$grid$k[i], n = sim$grid$n[i], rep = sim$grid$rep[i],\n             item = 1:20, m)\n})) |>\n  pivot_longer(c(infit, restscore, sx2_raw, sx2_bh, sx2_rmsea),\n               names_to = \"method\", values_to = \"flag\") |>\n  mutate(is_misfit = mapply(function(k, it) it %in% sim$misfit[seq_len(k)],\n                            k, item))\n\ncat(\"failed method-replications:\", sum(is.na(long$flag)), \"of\", nrow(long), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nfailed method-replications: 0 of 300000 \n```\n\n\n:::\n:::\n\n\n## Results {#sec-sx2-results}\n\n### Type I error under a true Rasch model (k = 0) {#sec-sx2-null}\n\nWith no misfitting items present, the flag rate on any item is a false positive.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlong |>\n  filter(k == 0) |>\n  group_by(method, n) |>\n  summarise(fp = 100 * mean(flag, na.rm = TRUE), .groups = \"drop\") |>\n  pivot_wider(names_from = n, values_from = fp, names_prefix = \"n=\") |>\n  mutate(across(where(is.numeric), \\(x) round(x, 1)))\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|method    | n=150| n=250| n=500| n=1000| n=2000|\n|:---------|-----:|-----:|-----:|------:|------:|\n|infit     |   1.6|   1.6|   1.0|    1.0|    0.9|\n|restscore |   0.7|   0.3|   0.3|    0.1|    0.1|\n|sx2_bh    |   0.7|   0.5|   0.8|    0.7|    1.1|\n|sx2_raw   |   6.9|   7.1|   8.7|    7.1|    8.8|\n|sx2_rmsea |  26.2|  11.1|   1.4|    0.0|    0.0|\n\n</div>\n:::\n:::\n\n\n### Family-wise rates under the null {#sec-sx2-familywise}\n\n::: {.callout-warning appearance=\"simple\" icon=false}\n## Added when this study was moved into the book\n\nThe table above gives per-item rates. What a user sees is whether a dataset\ngets at least one flagged item, and that rate is computed below from the same\ncached results. With 200 replications per cell its Monte Carlo SE is about 1.5\npoints near 5% and about 3 points near 20%.\n\nThis corrects conclusion 3 in @sec-sx2-conclusions. Item-restscore with BH\nflags at least one item in 12.5% of datasets at n = 150, against a nominal 5%.\nThe [item-restscore chapter](restscore-asymptotic-null.qmd) reproduces this at\n13.5% with 4000 replications and traces it to the expected gamma being treated\nas known. Conditional infit cutoffs are set per item with no multiplicity\ncorrection, so its family-wise rate is 15% to 27.5%. S-X2 with BH is above 5%\nat every n and rises with it, and uncorrected S-X2 rejects 7% to 9% per item,\nso its p-values are liberal under a true Rasch model in this design. That bears\non conclusion 2, since part of S-X2's lower false-positive rate under misfit is\nmeasured against methods with different null behaviour.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nk0 <- which(sim$grid$k == 0)\nmethods <- c(\"infit\", \"restscore\", \"sx2_raw\", \"sx2_bh\", \"sx2_rmsea\")\nfw <- sapply(methods, function(m)\n  tapply(k0, sim$grid$n[k0], function(ii)\n    100 * mean(vapply(ii, function(i) any(sim$res[[i]][, m] == 1, na.rm = TRUE),\n                      logical(1)))))\nfw <- data.frame(n = as.integer(rownames(fw)), round(fw, 1), row.names = NULL)\nkable(fw, caption = \"Percent of null datasets (k = 0) with at least one flagged item\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Percent of null datasets (k = 0) with at least one flagged item\n\n|    n| infit| restscore| sx2_raw| sx2_bh| sx2_rmsea|\n|----:|-----:|---------:|-------:|------:|---------:|\n|  150|  27.5|      12.5|    77.5|   10.5|      99.5|\n|  250|  27.5|       5.5|    75.0|   10.5|      89.0|\n|  500|  19.0|       5.0|    85.0|   13.0|      25.0|\n| 1000|  19.0|       2.0|    79.0|   13.5|       1.0|\n| 2000|  15.0|       1.5|    86.0|   19.0|       0.0|\n\n\n:::\n:::\n\n\n### Detection rate, 1 misfitting item\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlong |>\n  filter(k == 1, is_misfit) |>\n  group_by(method, n) |>\n  summarise(det = 100 * mean(flag, na.rm = TRUE), .groups = \"drop\") |>\n  pivot_wider(names_from = n, values_from = det, names_prefix = \"n=\") |>\n  mutate(across(where(is.numeric), \\(x) round(x, 1)))\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|method    | n=150| n=250| n=500| n=1000| n=2000|\n|:---------|-----:|-----:|-----:|------:|------:|\n|infit     | 100.0|   100|   100|    100|    100|\n|restscore |  97.5|   100|   100|    100|    100|\n|sx2_bh    |  98.5|   100|   100|    100|    100|\n|sx2_raw   | 100.0|   100|   100|    100|    100|\n|sx2_rmsea | 100.0|   100|   100|    100|    100|\n\n</div>\n:::\n:::\n\n\nFalse positives on the 19 fitting items in the same datasets:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlong |>\n  filter(k == 1, !is_misfit) |>\n  group_by(method, n) |>\n  summarise(fp = 100 * mean(flag, na.rm = TRUE), .groups = \"drop\") |>\n  pivot_wider(names_from = n, values_from = fp, names_prefix = \"n=\") |>\n  mutate(across(where(is.numeric), \\(x) round(x, 1)))\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|method    | n=150| n=250| n=500| n=1000| n=2000|\n|:---------|-----:|-----:|-----:|------:|------:|\n|infit     |   2.5|   3.1|   2.5|    6.5|   13.7|\n|restscore |   2.5|   2.6|   2.9|    5.6|   15.1|\n|sx2_bh    |   0.4|   0.7|   0.3|    0.5|    1.4|\n|sx2_raw   |   5.4|   5.1|   4.8|    6.0|   10.2|\n|sx2_rmsea |  22.0|   8.8|   0.2|    0.0|    0.0|\n\n</div>\n:::\n:::\n\n\n### Detection rate, 3 misfitting items\n\nBroken out by item, since targeting matters.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlong |>\n  filter(k == 3, is_misfit) |>\n  mutate(target = c(\"0 logits\", \"-1 logits\", \"-2 logits\")[match(item, sim$misfit)]) |>\n  group_by(method, target, n) |>\n  summarise(det = 100 * mean(flag, na.rm = TRUE), .groups = \"drop\") |>\n  pivot_wider(names_from = n, values_from = det, names_prefix = \"n=\") |>\n  mutate(across(where(is.numeric), \\(x) round(x, 1))) |>\n  arrange(factor(target, levels = c(\"0 logits\", \"-1 logits\", \"-2 logits\")), method)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|method    |target    | n=150| n=250| n=500| n=1000| n=2000|\n|:---------|:---------|-----:|-----:|-----:|------:|------:|\n|infit     |0 logits  |  97.0| 100.0| 100.0|    100|    100|\n|restscore |0 logits  |  87.0| 100.0| 100.0|    100|    100|\n|sx2_bh    |0 logits  |  88.0|  99.0| 100.0|    100|    100|\n|sx2_raw   |0 logits  |  96.5|  99.5| 100.0|    100|    100|\n|sx2_rmsea |0 logits  |  98.5|  99.5| 100.0|    100|    100|\n|infit     |-1 logits |  89.0|  98.5| 100.0|    100|    100|\n|restscore |-1 logits |  79.0|  98.5| 100.0|    100|    100|\n|sx2_bh    |-1 logits |  80.5|  98.0| 100.0|    100|    100|\n|sx2_raw   |-1 logits |  94.5| 100.0| 100.0|    100|    100|\n|sx2_rmsea |-1 logits |  99.0| 100.0| 100.0|    100|    100|\n|infit     |-2 logits |  57.5|  81.5|  99.5|    100|    100|\n|restscore |-2 logits |  52.0|  82.5|  99.5|    100|    100|\n|sx2_bh    |-2 logits |  54.0|  78.5|  99.0|    100|    100|\n|sx2_raw   |-2 logits |  75.0|  87.5|  99.5|    100|    100|\n|sx2_rmsea |-2 logits |  89.5|  91.5|  98.0|    100|    100|\n\n</div>\n:::\n:::\n\n\nFalse positives on the 17 fitting items:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlong |>\n  filter(k == 3, !is_misfit) |>\n  group_by(method, n) |>\n  summarise(fp = 100 * mean(flag, na.rm = TRUE), .groups = \"drop\") |>\n  pivot_wider(names_from = n, values_from = fp, names_prefix = \"n=\") |>\n  mutate(across(where(is.numeric), \\(x) round(x, 1)))\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|method    | n=150| n=250| n=500| n=1000| n=2000|\n|:---------|-----:|-----:|-----:|------:|------:|\n|infit     |   4.7|   7.3|  10.3|   23.7|   54.2|\n|restscore |   8.4|  10.8|  21.4|   45.7|   80.6|\n|sx2_bh    |   0.5|   0.7|   1.2|    3.6|   16.9|\n|sx2_raw   |   4.8|   4.4|   6.4|   12.6|   31.7|\n|sx2_rmsea |  21.6|   8.1|   0.7|    0.0|    0.0|\n\n</div>\n:::\n:::\n\n\n### Figure: detection vs false positives, 3 misfitting items\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot_dat <- long |>\n  filter(k == 3, method %in% c(\"infit\", \"restscore\", \"sx2_bh\", \"sx2_rmsea\")) |>\n  mutate(type = ifelse(is_misfit, \"Detection (misfitting items)\",\n                       \"False positives (fitting items)\")) |>\n  group_by(method, n, type) |>\n  summarise(pct = 100 * mean(flag, na.rm = TRUE), .groups = \"drop\")\n\nggplot(plot_dat, aes(factor(n), pct, fill = method)) +\n  geom_col(position = \"dodge\") +\n  facet_wrap(~type) +\n  labs(x = \"Sample size\", y = \"Percent\", fill = \"Method\") +\n  theme_minimal(base_size = 12)\n```\n\n::: {.cell-output-display}\n![](sx2-itemfit_files/figure-html/fig-1.png)\n:::\n:::\n\n\n## Supplementary study: weaker multidimensionality {#sec-sx2-weak}\n\nThe main study uses an inter-dimensional correlation of 0.15, which is strong\nmisfit — detection saturates at 100% for all methods from n = 500 onwards, so\nthe main study discriminates between methods almost entirely on false\npositives.\n\nThe `sx2_rmsea` rule performs strikingly well at n >= 500 there, but it applies\na **fixed** threshold of .05 to an effect size. Its performance therefore\ndepends on how far the true misfit sits above that threshold, and a strong\nmisfit condition flatters it. This supplement re-runs the k = 3 condition with\ninter-dimensional correlations of 0.50 and 0.75 (progressively weaker\nmultidimensionality) and records the raw `RMSEA.S_X2` values, to check whether\nthe rule survives when the effect is subtle.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmake_master_r <- function(rho, n_misfit = 3, N = 10000, seed = 20250727) {\n  set.seed(seed)\n  locs <- runif(20, -2, 2)\n  misfit_idx <- integer(0)\n  for (tg in c(0, -1, -2)) {\n    cand <- setdiff(order(abs(locs - tg)), misfit_idx)[1]\n    misfit_idx <- c(misfit_idx, cand)\n  }\n  use <- misfit_idx[seq_len(n_misfit)]\n  W <- cbind(rep(1, 20), rep(0, 20))\n  W[use, ] <- matrix(c(0, 1), nrow = length(use), ncol = 2, byrow = TRUE)\n  Sigma <- matrix(c(1.5^2, rho * 1.5^2, rho * 1.5^2, 1.5^2), 2, 2)\n  set.seed(seed + round(rho * 100))\n  th <- MASS::mvrnorm(N, mu = c(0, 0), Sigma = Sigma)\n  d <- as.data.frame(eRm::sim.xdim(persons = th, items = locs,\n                                   Sigma = Sigma, weightmat = W))\n  names(d) <- paste0(\"V\", 1:20)\n  list(data = d, locs = locs, misfit = use)\n}\n\nRHOS  <- c(0.50, 0.75)\nNS2   <- c(250, 500, 1000, 2000)\nR2    <- 150\nRES2  <- \"results/sx2/sx2_itemfit_sim_weak_results.rds\"\n\nmasters2 <- lapply(RHOS, make_master_r)\nnames(masters2) <- as.character(RHOS)\n\none_rep2 <- function(rep, rho, n) {\n  set.seed(1e6 * round(rho * 100) + 1e3 * n + rep)\n  md <- masters2[[as.character(rho)]]$data\n  d  <- md[sample(nrow(md), n), ]\n  iters <- if (n < 500) 100 else 200\n  out <- data.frame(item = 1:20, infit = NA_integer_, restscore = NA_integer_,\n                    sx2_bh = NA_integer_, sx2_rmsea = NA_integer_,\n                    rmsea = NA_real_)\n  try({\n    co <- RMitemInfitCutoff(d, iterations = iters, parallel = FALSE,\n                            seed = rep, verbose = FALSE)\n    fi <- RMitemInfit(d, cutoff = co, output = \"dataframe\")\n    out$infit <- as.integer(fi$Flagged[match(names(d), fi$Item)] != \"\")\n  }, silent = TRUE)\n  try({\n    rs <- RMitemRestscore(d, output = \"dataframe\", p_adj = \"BH\")\n    out$restscore <- as.integer(rs$Flagged[match(names(d), rs$Item)] != \"\")\n  }, silent = TRUE)\n  try({\n    mm <- mirt(d, 1, itemtype = \"Rasch\", verbose = FALSE)\n    f  <- mirt::itemfit(mm, fit_stats = \"S_X2\")\n    i  <- match(names(d), f$item)\n    out$sx2_bh    <- as.integer(p.adjust(f$p.S_X2, \"BH\")[i] < .05)\n    out$rmsea     <- f$RMSEA.S_X2[i]\n    out$sx2_rmsea <- as.integer(f$RMSEA.S_X2[i] > .05)\n  }, silent = TRUE)\n  out\n}\n\ngrid2 <- expand.grid(rep = 1:R2, n = NS2, rho = RHOS)\n\nif (file.exists(RES2)) {\n  sim2 <- readRDS(RES2)\n} else {\n  res2 <- mclapply(seq_len(nrow(grid2)),\n                   function(i) one_rep2(grid2$rep[i], grid2$rho[i], grid2$n[i]),\n                   mc.cores = NCORES)\n  sim2 <- list(res = res2, grid = grid2, misfit = masters2[[\"0.5\"]]$misfit)\n  saveRDS(sim2, RES2)\n}\n\nlong2 <- do.call(rbind, lapply(seq_len(nrow(sim2$grid)), function(i)\n  cbind(sim2$grid[i, ], sim2$res[[i]]))) |>\n  mutate(is_misfit = item %in% sim2$misfit)\n```\n:::\n\n\nDetection of the three misfitting items:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlong2 |>\n  filter(is_misfit) |>\n  pivot_longer(c(infit, restscore, sx2_bh, sx2_rmsea),\n               names_to = \"method\", values_to = \"flag\") |>\n  group_by(rho, method, n) |>\n  summarise(v = 100 * mean(flag, na.rm = TRUE), .groups = \"drop\") |>\n  pivot_wider(names_from = n, values_from = v, names_prefix = \"n=\") |>\n  mutate(across(where(is.numeric), \\(x) round(x, 1))) |>\n  arrange(rho, method)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n| rho|method    | n=250| n=500| n=1000| n=2000|\n|---:|:---------|-----:|-----:|------:|------:|\n| 0.5|infit     |  63.6|  83.8|   96.4|  100.0|\n| 0.5|restscore |  42.9|  81.8|   98.2|  100.0|\n| 0.5|sx2_bh    |  50.2|  77.3|   96.9|  100.0|\n| 0.5|sx2_rmsea |  78.9|  77.1|   73.8|   70.7|\n| 0.8|infit     |  23.8|  36.4|   69.6|   94.7|\n| 0.8|restscore |   2.9|  16.7|   57.3|   93.8|\n| 0.8|sx2_bh    |   9.3|  23.3|   39.6|   77.8|\n| 0.8|sx2_rmsea |  40.4|  24.9|    6.9|    0.4|\n\n</div>\n:::\n:::\n\n\nFalse positives on the 17 fitting items:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlong2 |>\n  filter(!is_misfit) |>\n  pivot_longer(c(infit, restscore, sx2_bh, sx2_rmsea),\n               names_to = \"method\", values_to = \"flag\") |>\n  group_by(rho, method, n) |>\n  summarise(v = 100 * mean(flag, na.rm = TRUE), .groups = \"drop\") |>\n  pivot_wider(names_from = n, values_from = v, names_prefix = \"n=\") |>\n  mutate(across(where(is.numeric), \\(x) round(x, 1))) |>\n  arrange(rho, method)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n| rho|method    | n=250| n=500| n=1000| n=2000|\n|---:|:---------|-----:|-----:|------:|------:|\n| 0.5|infit     |   3.0|   3.4|    6.7|   15.4|\n| 0.5|restscore |   3.4|   5.9|   12.0|   25.5|\n| 0.5|sx2_bh    |   0.5|   0.9|    1.3|    2.3|\n| 0.5|sx2_rmsea |   8.5|   0.5|    0.0|    0.0|\n| 0.8|infit     |   2.5|   1.5|    2.2|    4.4|\n| 0.8|restscore |   1.2|   1.4|    2.5|    4.4|\n| 0.8|sx2_bh    |   0.7|   0.9|    0.9|    1.8|\n| 0.8|sx2_rmsea |   9.7|   0.9|    0.0|    0.0|\n\n</div>\n:::\n:::\n\n\nMedian `RMSEA.S_X2` for misfitting vs fitting items, against the .05 threshold:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlong2 |>\n  group_by(rho, n, type = ifelse(is_misfit, \"misfitting\", \"fitting\")) |>\n  summarise(median_rmsea = round(median(rmsea, na.rm = TRUE), 3),\n            .groups = \"drop\") |>\n  pivot_wider(names_from = n, values_from = median_rmsea, names_prefix = \"n=\")\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|  rho|type       | n=250| n=500| n=1000| n=2000|\n|----:|:----------|-----:|-----:|------:|------:|\n| 0.50|fitting    | 0.006| 0.004|  0.007|  0.007|\n| 0.50|misfitting | 0.075| 0.065|  0.061|  0.058|\n| 0.75|fitting    | 0.000| 0.005|  0.001|  0.003|\n| 0.75|misfitting | 0.043| 0.037|  0.032|  0.030|\n\n</div>\n:::\n:::\n\n\n## Conclusions {#sec-sx2-conclusions}\n\n**1. S-X2 has no power advantage, and a power disadvantage against subtle\nmisfit.** With strong multidimensionality (rho = 0.15) all methods are\nequivalent and saturate. With rho = 0.75, conditional infit clearly dominates:\n23.8 / 36.4 / 69.6 / 94.7 percent detection at n = 250 / 500 / 1000 / 2000,\nagainst 9.3 / 23.3 / 39.6 / 77.8 for S-X2. The concern raised by the Kang and\nChen GRM follow-up — weak power against multidimensionality — does not appear\nunder strong misfit but is clearly visible once the misfit is subtle.\n\n**2. S-X2 does control the false positive cascade.** This is its real\ncontribution. With three strongly misfitting items at n = 2000, false positives\non fitting items are 54.2 percent for infit and 80.6 percent for item-restscore,\nagainst 16.9 percent for S-X2. On the practically relevant metric — recovering\nall three misfitting items with no false positives — S-X2 achieves 72 percent\nat n = 1000-2000 with rho = 0.5, where infit manages 26 and 3.3 percent.\n\n**3. Infit and item-restscore are not miscalibrated.** Under a true Rasch model\nwith no misfitting items, false positive rates are 0.1-1.6 percent at every\nsample size, including n = 2000. The large-sample false positives reported in\n@johansson2025 are therefore entirely the overfit cascade caused by the\nmisfitting items themselves, not a defect in the simulation-based cutoffs.\nThis conclusion does not hold family-wise, see @sec-sx2-familywise.\n\n**4. A fixed RMSEA threshold of .05 is not usable.** It fails in both\ndirections. At n = 150 under a true model it flags 26.2 percent of items,\nbecause the null RMSEA has not yet shrunk. At rho = 0.75 the median RMSEA of\ngenuinely misfitting items is .030-.043 — below the threshold — so detection\nfalls to 0.4 percent at n = 2000, and gets *worse* as n grows, since the\nestimate concentrates around a true value under the cutoff.\n\n**5. The implied design.** RMSEA.S_X2 has the property that is wanted — it does\nnot inflate with sample size (median .058-.075 for misfitting items across\nn = 250-2000 at rho = 0.5) — but the threshold is wrong and is itself\nsample-size dependent. Median RMSEA for fitting items is .000-.007 at\nn >= 250, far below .05. This is exactly the problem `RMitemInfitCutoff` solves\nfor infit, which suggests a simulation-based cutoff for RMSEA.S_X2 would set a\nmuch lower and n-appropriate threshold, and would likely recover the rho = 0.75\ndetection that the fixed rule misses. **This is a hypothesis, not a result — it\nhas not been tested here.**\n\nOverall: S-X2 is a large-sample complement to conditional infit, not a\nreplacement for it. Its niche is several strongly misfitting items at\nn >= 1000, which is precisely where the existing methods fail.\n\n## Notes on interpretation {#sec-sx2-notes}\n\n`sx2_rmsea` uses a fixed RMSEA cutoff of .05, borrowed from SEM convention.\nItem-level RMSEA cutoffs are not well established, and the null RMSEA shrinks\nwith sample size, so this rule is expected to behave asymmetrically across n.\nIt is included to separate two questions that the S-X2 significance test\nconfounds: whether the departure is detectable, and whether it is large.\n\nA caveat on estimation: `mirt::itemfit()` estimates item parameters by MML\nunder a normal θ prior. For the Rasch family the S-X2 expected proportions are\nin principle distribution-free — the θ density cancels between numerator and\ndenominator, leaving the CML conditional probabilities — but that only holds at\nthe true parameters. A CML-based implementation would remove the normality\nassumption, which matters here since the generating θ distribution is normal\nand therefore favourable to the mirt route.\n\n## Revision history {.unnumbered}\n\n- 2026-10-04: first version in this book, moved from `easyRasch2/dev/sx2_itemfit_sim.qmd`. Added the family-wise null rates in @sec-sx2-familywise, computed from the existing cache, and a pointer from conclusion 3 to them.\n",
    "supporting": [
      "sx2-itemfit_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}