{
  "hash": "8c430291a55d451bfd5c924c6f9e8dd2",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"An exact null for the PCA/t-test unidimensionality protocol\"\nsubtitle: \"Why the person-level t-test is not a 5% test, and what that does to the binomial step\"\nauthor: \"Magnus Johansson\"\ndate: 2026-10-04\ndate-modified: 2026-10-04\n---\n\n\n\n::: {.callout-note appearance=\"simple\" icon=false}\n## About this chapter\n\n**Status:** complete<br>\n**Computed with:** easyRasch2 1.3.1.9002, R 4.6.1<br>\n**Slides:** [An exact null for two Rasch protocols](../slides/rasch-exact-null.html){target=\"_blank\"}<br>\n**Cite as:** Johansson, M. (2026). An exact null for the PCA/t-test\nunidimensionality protocol. In *Rasch Measurement Explorations*.\n<https://pgmj.github.io/rasch_book/chapters/ttest-protocol-exact-null.html>\n:::\n\n::: {.callout-tip appearance=\"simple\" icon=false}\n## Summary\n\nThe PCA/t-test protocol compares two person estimates per respondent with a\nt-test against 1.96 and refers the proportion of significant tests to 5%. The\nperson-level statistic is the Rasch change index with item subtests in place of\noccasions, and its null can be computed exactly, conditional on the total score\nand free of the latent distribution. The 1.96 rule has a true size of 1.4% to\n3.9% under a unidimensional Rasch model, and many respondents cannot be flagged\nat all. The 5% benchmark is therefore too lenient, which biases the protocol\ntoward declaring unidimensionality. The choice of binomial interval matters much\nless than this. Selecting the split from the data pushes the other way, and how\nthe two errors balance is not settled here.\n:::\n\n## Purpose {#sec-tt-purpose}\n\nThe PCA/t-test protocol [@smith2002; @tennant2006] splits a scale into two item\nsets from a principal component analysis of residuals, estimates a person\nlocation from each set, compares them per respondent with a t-test against\n1.96, and refers the resulting proportion of significant tests to a 5%\nbenchmark through a binomial confidence interval. @hagell2014 showed that the\nconclusion depends on sample size and on which of five binomial interval methods\nis used, and argued the protocol should be read as ordinary hypothesis testing\nrather than as a definite test.\n\nThat leaves the reference proportion itself unexamined. This note shows that the\n1.96 rule is not a 5% test, computes its exact size, and records what that does\nto the binomial step. The conclusion is that the choice of interval method is a\nsecond-order question about the shape of a distribution whose center is wrong by\na factor of 1.3 to 3.7. The direction is uniform, so the protocol is biased toward\ndeclaring unidimensionality.\n\n## The statistic is the change index with subtests in place of occasions {#sec-tt-statistic}\n\nThe protocol computes\n\n$$t = \\frac{\\hat\\theta_A - \\hat\\theta_B}{\\sqrt{SE(\\hat\\theta_A)^2 + SE(\\hat\\theta_B)^2}}$$\n\nwhich is the Rasch change index of the [RCI chapter](rci-exact-null.qmd) with\nitem subtests in place of occasions. Both mechanisms documented there\n(@sec-rci-mechanisms) carry over.\n\n**Self-normalisation.** $SE(\\hat\\theta_A)$ and $SE(\\hat\\theta_B)$ are\ndeterministic functions of the realised subtest scores, so the denominator is\nnot independent of the numerator, both tails of the null are damped, and the\ncritical value falls below 1.96. The \"t\" label is a misnomer for the same\nreason: a t denominator is independent of its numerator, which is the one\nproperty this denominator does not have.\n\n**Discreteness.** With complete data each subtest score is sufficient, so\n$\\hat\\theta_A$ and $\\hat\\theta_B$ take only as many values as there are subtest\nscores and the null is a distribution over $(k_A+1) \\times (k_B+1)$ cells.\n\nConditional independence, which is what makes the enumeration possible, also\ncarries over, but it has a different standing in the two settings. In the change\ncase it is an auxiliary assumption. The null there is that $\\theta$ did not\nmove, and carry-over between two administrations of the same items can be\npresent while $\\theta$ is fixed, so separate administration does not deliver\nconditional independence on its own. @sec-rci-carryover covers\nwhat happens when it fails. Here the item sets are disjoint, so local\nindependence gives $P(r_A, r_B \\mid \\theta) = P(r_A \\mid \\theta)\\,P(r_B \\mid\n\\theta)$, and that statement is the null hypothesis rather than a condition\nattached to it. A failure is what the protocol exists to detect, so enumerating\nunder it is the right move.\n\nWhat the protocol cannot do is say which kind of failure it found. @marais2008a separate **trait dependence**, where a person parameter\nbeyond $\\theta$ enters the responses, from **response dependence**, where the\nresponse to one item governs the response to another. Only the first is\nmultidimensionality. Two locally dependent items in the same subtest reduce the\ninformation that subtest carries below what the model assumes, so $SE_A$\nunderstates the spread of $\\hat\\theta_A$ and $|t|$ is inflated, pushing the\nprotocol toward rejection in the same way a second dimension would. That follows\nfrom the information rather than from anything measured here. It leaves the size\ncalculations below untouched, since those hold under a null with no dependence\nof either kind, but it bears on what a rejection supports: that the item set\nfails local independence, not the stronger claim of multidimensionality that the\nprocedure's name carries.\n\n## Conditioning on the total score removes the latent distribution {#sec-tt-conditioning}\n\nThe RCI chapter enumerates the null at a set of person locations and pools over\nthem, which makes the pooled critical value a property of the sample as well as\nthe items. The subtest case admits a stronger construction. Under the Rasch\nmodel the conditional distribution of $r_A$ given the total score $r_A + r_B$ is\nfree of $\\theta$, by the same sufficiency that underlies CML estimation:\n\n$$P(r_A = a \\mid r_A + r_B = r) = \\frac{\\gamma_A(a)\\,\\gamma_B(r-a)}{\\gamma(r)}$$\n\nSo the null of $t$ can be enumerated per total score with no latent distribution\nassumption and no plug-in person estimate. Numerically it is easier to evaluate\n$P(r_A \\mid \\theta)P(r_B \\mid \\theta)$ at any convenient $\\theta$ and normalise\nwithin each total score, which gives the same ratio. Invariance is checked below\nrather than assumed.\n\nSufficiency and the recursion divide the work. Sufficiency is what makes the\nratio free of $\\theta$, and it also fixes the value of $t$ in every cell, since\n$\\hat\\theta$ and $SE$ are functions of the subtest score alone. Neither of\nthose says what the $\\gamma$ terms are, and a quantile needs them. Computing\nthem is what Lord-Wingersky does, as exact combinatorics rather than\nestimation.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Thresholds: k items, ncat response categories, locations spread over\n# [-spread, spread]. Same constructor as the RCI chapter.\nmk <- function(k, ncat, spread = 1.2) {\n  lapply(seq(-spread, spread, length.out = k),\n         function(b) b + seq(-0.9, 0.9, length.out = ncat - 1L))\n}\n\n# Lord-Wingersky: exact sum-score distribution given theta under a PCM\nscore_dist <- function(thr_list, theta) {\n  d <- 1\n  for (thr in thr_list) {\n    p  <- easyRasch2:::.pcm_cat_probs(theta, thr)\n    nd <- numeric(length(d) + length(p) - 1L)\n    for (a in seq_along(d)) nd[a + seq_along(p) - 1L] <-\n        nd[a + seq_along(p) - 1L] + d[a] * p\n    d <- nd\n  }\n  d                                   # index = score + 1\n}\n\n# Score -> (theta, SE) lookup, WLE. The lookup RMscoreSE() builds.\nlut <- function(thr_list) {\n  steps <- vapply(thr_list, length, integer(1L))\n  m <- vapply(0:sum(steps), function(r)\n    easyRasch2:::.theta_wle(easyRasch2:::.score_pattern(r, steps),\n                            thr_list, c(-10, 10)), numeric(2L))\n  list(theta = m[1L, ], se = m[2L, ])\n}\n\n# The t grid and the raw logit-gap grid for one split\nsplit_grid <- function(thr_all, idxA) {\n  A <- thr_all[idxA]; B <- thr_all[-idxA]\n  lA <- lut(A); lB <- lut(B)\n  list(A = A, B = B, lA = lA, lB = lB,\n       t = outer(seq_along(lA$theta), seq_along(lB$theta),\n                 function(i, j) (lA$theta[i] - lB$theta[j]) /\n                   sqrt(lA$se[i]^2 + lB$se[j]^2)),\n       d = outer(seq_along(lA$theta), seq_along(lB$theta),\n                 function(i, j) lA$theta[i] - lB$theta[j]))\n}\n\n# Null of t conditional on the total score. Free of theta.\ncond_null <- function(g, theta_eval = 0) {\n  dA <- score_dist(g$A, theta_eval); dB <- score_dist(g$B, theta_eval)\n  maxA <- length(dA) - 1L; maxB <- length(dB) - 1L\n  lapply(0:(maxA + maxB), function(r) {\n    a <- max(0L, r - maxB):min(maxA, r)\n    w <- dA[a + 1L] * dB[r - a + 1L]\n    list(a = a, p = w / sum(w),\n         t = g$t[cbind(a + 1L, r - a + 1L)],\n         d = g$d[cbind(a + 1L, r - a + 1L)])\n  })\n}\n\nalpha_by_r <- function(cn, crit = 1.96)\n  vapply(cn, function(x) sum(x$p[abs(x$t) > crit]), numeric(1L))\n\ngap_by_r <- function(cn) vapply(cn, function(x) sum(x$p * x$d), numeric(1L))\n\n# Total-score distribution under a latent density, by quadrature\nscore_weights <- function(thr_all, mu = 0, sigma = 1.4, nq = 121L) {\n  q <- seq(mu - 5 * sigma, mu + 5 * sigma, length.out = nq)\n  w <- dnorm(q, mu, sigma); w <- w / sum(w)\n  Reduce(`+`, Map(function(t, wt) wt * score_dist(thr_all, t), q, w))\n}\n\n# Pooled exact critical values achieving nominal alpha\ncrit_pooled <- function(cn, fr, alpha = 0.05) {\n  tv <- unlist(lapply(cn, `[[`, \"t\"))\n  pv <- unlist(Map(function(x, f) x$p * f, cn, fr))\n  o <- order(tv); tv <- tv[o]; pv <- pv[o] / sum(pv)\n  cw <- cumsum(pv)\n  c(lower = tv[which(cw >= alpha / 2)[1L]],\n    upper = tv[which(cw >= 1 - alpha / 2)[1L]])\n}\n\n# Exact Poisson-binomial distribution of the flagged count\npois_binom <- function(p) {\n  d <- 1\n  for (pi in p) d <- c(d * (1 - pi), 0) + c(0, d * pi)\n  d                                   # index = count + 1\n}\n```\n:::\n\n\n## Validation {#sec-tt-validation}\n\nThree anchors, following the discipline of the RCI chapter (@sec-rci-validation): reproduce an\nidentity to machine precision, and check the fast path against simulation.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nthr  <- mk(12, 4)\nidxA <- seq(1, 12, by = 2)            # interleaved 6 / 6\ng    <- split_grid(thr, idxA)\n\n# Anchor 1: is the conditional null actually free of theta?\ncn0 <- cond_null(g, 0); cnm <- cond_null(g, -2); cnp <- cond_null(g, 2.5)\ndev1 <- max(vapply(seq_along(cn0), function(i)\n  max(abs(cn0[[i]]$p - cnm[[i]]$p), abs(cn0[[i]]$p - cnp[[i]]$p)), numeric(1L)))\n\n# Anchor 3: does the exact pooled critical value recover nominal alpha?\nfr <- score_weights(thr, 0, 1.4); fr <- fr / sum(fr)\ncp <- crit_pooled(cn0, fr, 0.05)\nach <- sum(vapply(seq_along(cn0), function(i) fr[i] *\n  sum(cn0[[i]]$p[cn0[[i]]$t < cp[[\"lower\"]] | cn0[[i]]$t > cp[[\"upper\"]]]),\n  numeric(1L)))\n```\n:::\n\n\n**Anchor 1, theta-invariance.** Evaluating the conditional distribution at\n$\\theta = -2$, $0$ and $2.5$ agrees to a maximum absolute difference of\n1.9e-16. The construction is free of $\\theta$ rather than\napproximately so.\n\n**Anchor 2, against simulation.** Four hundred thousand respondents on the\n12-item scale, drawn from $N(0, 1.4)$, scored and classified by the same 1.96\nrule. Per-total-score $\\alpha$ agrees with the enumeration to a maximum absolute\ndifference of 0.0040 against a Monte Carlo standard error of 0.0039. The\nsimulation is not run at render time. It lives in\n`scripts/ttest/ttest_protocol_exact_null.R`.\n\n**Anchor 3, self-consistency.** Feeding the exact pooled critical values back\nthrough the enumeration gives $\\alpha =$ 0.0492 against a\nnominal 0.05, the residual being discreteness.\n\n## The 1.96 rule is not a 5% test {#sec-tt-size}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrun <- function(label, k, ncat, idxA, mu = 0, sigma = 1.4) {\n  thr <- mk(k, ncat); g <- split_grid(thr, idxA); cn <- cond_null(g, 0)\n  fr <- score_weights(thr, mu, sigma); fr <- fr / sum(fr)\n  a <- alpha_by_r(cn, 1.96); gp <- gap_by_r(cn); cp <- crit_pooled(cn, fr, 0.05)\n  nz <- a > 0\n  data.frame(config = label, subtests = paste0(length(idxA), \"/\", k - length(idxA)),\n             alpha = sum(fr * a), ratio = 0.05 / sum(fr * a),\n             pct_zero = 100 * sum(fr[!nz]),\n             lo = cp[[\"lower\"]], hi = cp[[\"upper\"]],\n             asym = abs(cp[[\"lower\"]]) - cp[[\"upper\"]],\n             gap = max(abs(gp[nz])), stringsAsFactors = FALSE)\n}\n\nres <- do.call(rbind, list(\n  run(\"12 items, 4 cat\",               12, 4, seq(1, 12, by = 2)),\n  run(\"12 items, 4 cat\",               12, 4, seq(1, 12, by = 3)),\n  run(\"20 items, 4 cat\",               20, 4, seq(1, 20, by = 2)),\n  run(\"20 items, 4 cat\",               20, 4, seq(1, 20, by = 3)),\n  run(\"20 items, 4 cat\",               20, 4, seq(1, 20, by = 5)),\n  run(\"30 items, 4 cat\",               30, 4, seq(1, 30, by = 2)),\n  run(\"40 items, 4 cat\",               40, 4, seq(1, 40, by = 2)),\n  run(\"20 items, 2 cat\",               20, 2, seq(1, 20, by = 2)),\n  run(\"20 items, 7 cat\",               20, 7, seq(1, 20, by = 2)),\n  run(\"20 items, 4 cat, easy/hard\",    20, 4, 1:10),\n  run(\"20 items, 4 cat, 2 logits off\", 20, 4, seq(1, 20, by = 2), mu = -2)))\n\nkable(data.frame(res$config, res$subtests, round(res$alpha, 4),\n                 round(res$ratio, 2), round(res$pct_zero, 1)),\n      col.names = c(\"Scale\", \"Split\", \"alpha\", \"Too lenient\",\n                    \"Unflaggable (%)\"),\n      row.names = FALSE)\n```\n\n::: {.cell-output-display}\n\n\n|Scale                         |Split |  alpha| Too lenient| Unflaggable (%)|\n|:-----------------------------|:-----|------:|-----------:|---------------:|\n|12 items, 4 cat               |6/6   | 0.0240|        2.08|            22.6|\n|12 items, 4 cat               |4/8   | 0.0231|        2.17|            12.8|\n|20 items, 4 cat               |10/10 | 0.0315|        1.59|            13.7|\n|20 items, 4 cat               |7/13  | 0.0312|        1.60|             7.0|\n|20 items, 4 cat               |4/16  | 0.0257|        1.95|             2.8|\n|30 items, 4 cat               |15/15 | 0.0355|        1.41|             7.3|\n|40 items, 4 cat               |20/20 | 0.0394|        1.27|             5.7|\n|20 items, 2 cat               |10/10 | 0.0137|        3.65|            44.2|\n|20 items, 7 cat               |10/10 | 0.0333|        1.50|            13.2|\n|20 items, 4 cat, easy/hard    |10/10 | 0.0328|        1.53|             3.6|\n|20 items, 4 cat, 2 logits off |10/10 | 0.0177|        2.83|            45.7|\n\n\n:::\n:::\n\n\nThe true size of the 1.96 rule runs from 1.4% to 3.9%. It never reaches 5%, and\nat 40 items split 20/20 it is still short by a factor of 1.27. Dichotomous items\nare the worst, with the polytomous-versus-dichotomous contrast at 0.0137, and a sample two\nlogits off target is nearly as bad at 0.0177. Both findings match the RCI chapter (@sec-rci-length and @sec-rci-targeting),\nwhere response categories moved the critical value mainly in the step from two\nto more than two, and where mistargeting dropped the pooled value from 1.695 to\n1.522 because a floor-bound sample is located where the statistic is most\ndamped.\n\nThe effective test length here is the subtest, not the scale, which is what\nmakes the protocol worse than the change case rather than equivalent to it. The\nlength table in @sec-rci-length reads 1.644 at 4 items, 1.725 at 6, 1.815 at 10 and\n1.868 at 20, four categories throughout and persons from $N(0, 1.4)$. A 20-item scale splitting 10/10 is\ngoverned by two 10-item instruments. The published recommendation to use the\nprotocol with at least 12 item response thresholds [@tennant2006; @horton2010]\namounts to four items at four categories, which is the worst row of that\ntable.\n\n## A large share of respondents cannot be flagged at all {#sec-tt-unflaggable}\n\nThe last column above counts respondents for whom **no attainable pair of\nsubtest scores produces $|t| > 1.96$**. Their contribution to the significant\ncount is zero with probability one, not 0.05. At 20 dichotomous items that is\n44% of the sample and on an off-target polytomous scale 46%.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npanel <- function(label, k, ncat, idxA) {\n  g <- split_grid(mk(k, ncat), idxA)\n  a <- alpha_by_r(cond_null(g, 0), 1.96)\n  data.frame(label = label, r = seq_along(a) - 1L, alpha = a)\n}\nd_fig <- rbind(\n  panel(\"20 items, 4 cat, 10/10\", 20, 4, seq(1, 20, by = 2)),\n  panel(\"12 items, 4 cat, 6/6\",   12, 4, seq(1, 12, by = 2)),\n  panel(\"20 items, 2 cat, 10/10\", 20, 2, seq(1, 20, by = 2)))\nd_fig$label <- factor(d_fig$label, levels = unique(d_fig$label))\n\nggplot(d_fig, aes(r, alpha)) +\n  geom_hline(yintercept = 0.05, linetype = \"dashed\", colour = \"grey40\") +\n  geom_step(direction = \"mid\") +\n  facet_wrap(~ label, scales = \"free_x\") +\n  labs(x = \"Total score across all items\", y = \"Exact type I error of 1.96\") +\n  theme_bw() + easyRasch2:::er2_axis_margins()\n```\n\n::: {.cell-output-display}\n![Exact size of the 1.96 rule by total score, under a perfectly unidimensional Rasch model. Weighted by a $N(0, 1.4)$ latent density to give the sample means quoted in the text. The dashed line is the 5% the protocol assumes. Scores at both ends carry a size of zero because no attainable split of that total clears 1.96.](ttest-protocol-exact-null_files/figure-html/fig-tt-alpha-1.png){#fig-tt-alpha fig-alt='Three panels, one per scale, plotting exact type I error against total score. Each panel shows a flat zero region at both ends of the score range and a ragged sawtooth in between that mostly falls below the dashed 0.05 reference line. The dichotomous panel has the widest zero regions and the lowest sawtooth.'}\n:::\n:::\n\n\nThe sawtooth is discreteness. Adjacent total scores differ in how many attainable\nsplits they have and where those splits fall relative to the cutoff, so the size\nof the test alternates rather than varying smoothly. The RCI chapter found the same\nstructure in the conditional critical value, which formed an arch across the\nscore range rather than a constant.\n\n@fig-tt-alpha also shows that the conservatism is not a uniform shrinkage. Around\nthe middle of the scale the size peaks at 0.062, 0.062 and 0.054 in the three\npanels, so the test is mildly anti-conservative there. Under the $N(0, 1.4)$\nweighting, 20%, 6% and 10% of respondents hold a total score whose size exceeds\n0.05. The whole of the deficit comes from the ends, where attainable scores run\nout and the size falls to zero. Averaging over the score distribution is what\nthe protocol does when it pools respondents into one proportion, and that\naverage is what has to be compared with 5%, but a reader should know that the\npooled figure is combining two opposite behaviours rather than describing a\ntest that is uniformly too strict.\n\n## Asymmetry and centering {#sec-tt-asymmetry}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsel <- c(1, 2, 5, 10, 3)\nkable(data.frame(res$config[sel], res$subtests[sel], round(res$lo[sel], 3),\n                 round(res$hi[sel], 3), round(res$asym[sel], 3),\n                 round(res$gap[sel], 3)),\n      col.names = c(\"Scale\", \"Split\", \"Lower\", \"Upper\", \"Asym.\",\n                    \"Gap (logits)\"),\n      row.names = FALSE)\n```\n\n::: {.cell-output-display}\n\n\n|Scale                      |Split |  Lower| Upper|  Asym.| Gap (logits)|\n|:--------------------------|:-----|------:|-----:|------:|------------:|\n|12 items, 4 cat            |6/6   | -1.711| 1.672|  0.040|        0.002|\n|12 items, 4 cat            |4/8   | -1.767| 1.626|  0.140|        0.114|\n|20 items, 4 cat            |4/16  | -1.770| 1.680|  0.090|        0.557|\n|20 items, 4 cat, easy/hard |10/10 | -2.001| 1.578|  0.423|        0.195|\n|20 items, 4 cat            |10/10 | -1.806| 1.813| -0.007|        0.001|\n\n\n:::\n:::\n\n\nThe RCI chapter (@sec-rci-validation) corrected an earlier belief that two-sided simulated critical values\nwere asymmetric: under the change null the two occasions are exchangeable, so the\ndifference is symmetric about zero however skewed $\\hat\\theta$ is, and\nexchangeability fails only when the occasions differ in missingness. Subtests\nbreak exchangeability by construction, because they differ in length, targeting\nand information. A balanced interleaved split is nearly symmetric, so the change\nresult transfers there. An unbalanced or difficulty-confounded split is not. The\nten easiest items against the ten hardest gives correct two-sided values of\n-2.001 and 1.578, so the upper value is stricter than 1.96 while the lower is\nmore lenient. A principal component of residuals often separates items by\nlocation as well as by content, which makes that row the relevant one.\n\nThe last column is $\\max_r |E[\\hat\\theta_A - \\hat\\theta_B \\mid r]|$ under a\nperfectly unidimensional model. On a 4/16 split it reaches 0.557 logits, purely\nfrom the difference in WLE bias between a four-item and a sixteen-item subtest.\nThat is model-implied signal with no multidimensionality behind it. Reporting\nquantity and units at every surface, as the RCI chapter insists, matters here: the\ngap is in logits, the t is unitless, and only the second is being compared with\n1.96.\n\n## What happens at the count level {#sec-tt-count}\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncount_null <- function(label, k, ncat, idxA, n, mu = 0, sigma = 1.4) {\n  thr <- mk(k, ncat); g <- split_grid(thr, idxA); cn <- cond_null(g, 0)\n  fr <- score_weights(thr, mu, sigma); fr <- fr / sum(fr)\n  a  <- alpha_by_r(cn, 1.96)\n  nr <- round(n * fr); p_i <- rep(a, times = nr)\n  d  <- pois_binom(p_i); cnt <- seq_along(d) - 1L; m <- length(p_i)\n  mean_p <- sum(d * cnt) / m\n  data.frame(config = label, n = m,\n             mean_p = 100 * mean_p,\n             q95    = 100 * cnt[which(cumsum(d) >= 0.95)[1L]] / m,\n             p_over = sum(d[cnt / m > 0.05]),\n             sd_pb  = sqrt(sum(d * cnt^2) - sum(d * cnt)^2),\n             sd_bin = sqrt(m * mean_p * (1 - mean_p)),\n             stringsAsFactors = FALSE)\n}\n\ncfgs <- list(list(\"20 items, 4 cat, 10/10\", 20, 4, seq(1, 20, by = 2)),\n             list(\"12 items, 4 cat, 6/6\",   12, 4, seq(1, 12, by = 2)),\n             list(\"20 items, 2 cat, 10/10\", 20, 2, seq(1, 20, by = 2)),\n             list(\"40 items, 4 cat, 20/20\", 40, 4, seq(1, 40, by = 2)))\ncts <- do.call(rbind, lapply(cfgs, function(cf)\n  do.call(rbind, lapply(c(200, 500, 1000), function(n)\n    count_null(cf[[1]], cf[[2]], cf[[3]], cf[[4]], n)))))\n\nkable(data.frame(cts$config, cts$n, round(cts$mean_p, 2), round(cts$q95, 2),\n                 round(cts$p_over, 4), round(cts$sd_pb, 2), round(cts$sd_bin, 2)),\n      col.names = c(\"Scale\", \"n\", \"Mean (%)\", \"95th (%)\", \"P(>5%)\",\n                    \"SD PB\", \"SD bin\"),\n      row.names = FALSE)\n```\n\n::: {.cell-output-display}\n\n\n|Scale                  |    n| Mean (%)| 95th (%)| P(>5%)| SD PB| SD bin|\n|:----------------------|----:|--------:|--------:|------:|-----:|------:|\n|20 items, 4 cat, 10/10 |  204|     3.15|     5.39| 0.0586|  2.48|   2.49|\n|20 items, 4 cat, 10/10 |  504|     3.15|     4.56| 0.0104|  3.90|   3.92|\n|20 items, 4 cat, 10/10 | 1002|     3.15|     4.09| 0.0007|  5.50|   5.53|\n|12 items, 4 cat, 6/6   |  201|     2.39|     4.48| 0.0090|  2.15|   2.17|\n|12 items, 4 cat, 6/6   |  498|     2.40|     3.61| 0.0005|  3.39|   3.42|\n|12 items, 4 cat, 6/6   | 1001|     2.40|     3.20| 0.0000|  4.81|   4.84|\n|20 items, 2 cat, 10/10 |  199|     1.36|     3.02| 0.0003|  1.61|   1.63|\n|20 items, 2 cat, 10/10 |  499|     1.37|     2.20| 0.0000|  2.57|   2.60|\n|20 items, 2 cat, 10/10 | 1000|     1.37|     2.00| 0.0000|  3.62|   3.67|\n|40 items, 4 cat, 20/20 |  210|     3.96|     6.19| 0.2114|  2.82|   2.82|\n|40 items, 4 cat, 20/20 |  507|     3.96|     5.52| 0.1105|  4.38|   4.39|\n|40 items, 4 cat, 20/20 | 1008|     3.94|     4.96| 0.0439|  6.16|   6.18|\n\n\n:::\n:::\n\n\nAt $n = 1000$, observing more than 5% significant tests is an event of\nprobability 0.0007, 0.0000, 0.0000 and 0.044 under a perfectly unidimensional\nmodel. The protocol treats 5% as the boundary of acceptability. The exact null\nputs it in the upper tail.\n\n**The binomial family is fine.** Conditioning on the observed scores makes the count\nPoisson-binomial rather than binomial, since each respondent carries their own\n$\\alpha_r$. The last two columns show the two standard deviations agree to\nwithin a percent throughout. The heterogeneity in $\\alpha_r$ is too small\nrelative to its mean to move the variance, because\n$\\mathrm{Var}_{\\text{PB}} = n\\bar\\alpha - \\sum \\alpha_i^2$ differs from\n$n\\bar\\alpha(1-\\bar\\alpha)$ by $n\\,\\mathrm{Var}(\\alpha_i)$, which is order\n$10^{-4}$ against a mean of order $10^{-2}$. Marginally, with person locations\ndrawn iid from a latent density, the count is binomial in any case.\n\nSo the distributional shape @hagell2014 investigates is not where the\nprotocol goes wrong. All five of the interval methods compared there are being applied to\nroughly the right distribution and compared against the wrong number.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndist_one <- function(label, k, ncat, idxA, n = 500) {\n  thr <- mk(k, ncat); g <- split_grid(thr, idxA)\n  fr <- score_weights(thr, 0, 1.4); fr <- fr / sum(fr)\n  p_i <- rep(alpha_by_r(cond_null(g, 0), 1.96), times = round(n * fr))\n  d <- pois_binom(p_i)\n  data.frame(label = label, prop = 100 * (seq_along(d) - 1L) / length(p_i),\n             dens = d)\n}\nd_cnt <- rbind(\n  dist_one(\"20 items, 4 cat, 10/10\", 20, 4, seq(1, 20, by = 2)),\n  dist_one(\"12 items, 4 cat, 6/6\",   12, 4, seq(1, 12, by = 2)),\n  dist_one(\"20 items, 2 cat, 10/10\", 20, 2, seq(1, 20, by = 2)))\n\nggplot(subset(d_cnt, prop <= 8), aes(prop, dens, colour = label)) +\n  geom_vline(xintercept = 5, linetype = \"dashed\", colour = \"grey40\") +\n  geom_step(direction = \"mid\") +\n  labs(x = \"Observed significant tests (%)\", y = \"Exact probability\",\n       colour = NULL) +\n  theme_bw() + easyRasch2:::er2_axis_margins() +\n  theme(legend.position = \"bottom\")\n```\n\n::: {.cell-output-display}\n![Exact null distribution of the observed proportion of significant t-tests at $n = 500$, under a perfectly unidimensional Rasch model with a $N(0, 1.4)$ latent density. The dashed line is the protocol's 5% benchmark.](ttest-protocol-exact-null_files/figure-html/fig-tt-count-1.png){#fig-tt-count fig-alt='Three overlaid distributions of the observed proportion of significant tests, one per scale, each roughly bell shaped and centered between one and four percent. All three lie almost entirely to the left of a dashed vertical line at five percent.'}\n:::\n:::\n\n\n## Extreme-score handling does not rescue it {#sec-tt-extremes}\n\nThe lookup above uses WLE, which is finite at extreme scores. Software using\nmaximum likelihood person estimates has to drop respondents extreme on either\nsubtest, so the check is whether that changes the size.\n\n\n::: {.cell}\n\n```{.r .cell-code}\njoint_w <- function(thr_all, idxA, mu = 0, sigma = 1.4, nq = 121L) {\n  A <- thr_all[idxA]; B <- thr_all[-idxA]\n  q <- seq(mu - 5 * sigma, mu + 5 * sigma, length.out = nq)\n  w <- dnorm(q, mu, sigma); w <- w / sum(w)\n  Reduce(`+`, Map(function(t, wt) wt * outer(score_dist(A, t), score_dist(B, t)),\n                  q, w))\n}\nchk <- function(label, k, ncat, idxA, mu = 0) {\n  thr <- mk(k, ncat); g <- split_grid(thr, idxA)\n  W <- joint_w(thr, idxA, mu); W <- W / sum(W)\n  sig <- abs(g$t) > 1.96\n  keep <- matrix(TRUE, nrow(W), ncol(W))\n  keep[c(1L, nrow(W)), ] <- FALSE; keep[, c(1L, ncol(W))] <- FALSE\n  data.frame(config = label, all = sum(W * sig),\n             pct_ex = 100 * (1 - sum(W[keep])),\n             dropped = sum(W[keep] * sig[keep]) / sum(W[keep]))\n}\nex <- rbind(\n  chk(\"12 items, 4 cat, 6/6\",       12, 4, seq(1, 12, by = 2)),\n  chk(\"20 items, 4 cat, 10/10\",     20, 4, seq(1, 20, by = 2)),\n  chk(\"20 items, 4 cat, 4/16\",      20, 4, seq(1, 20, by = 5)),\n  chk(\"40 items, 4 cat, 20/20\",     40, 4, seq(1, 40, by = 2)),\n  chk(\"20 items, 2 cat, 10/10\",     20, 2, seq(1, 20, by = 2)),\n  chk(\"20 items, 4 cat, off target\", 20, 4, seq(1, 20, by = 2), mu = -2))\nkable(data.frame(ex$config, round(ex$all, 4), round(ex$pct_ex, 1),\n                 round(ex$dropped, 4)),\n      col.names = c(\"Scale\", \"alpha, all\", \"Extreme (%)\",\n                    \"alpha, dropped\"),\n      row.names = FALSE)\n```\n\n::: {.cell-output-display}\n\n\n|Scale                       | alpha, all| Extreme (%)| alpha, dropped|\n|:---------------------------|----------:|-----------:|--------------:|\n|12 items, 4 cat, 6/6        |     0.0240|         8.4|         0.0254|\n|20 items, 4 cat, 10/10      |     0.0315|         3.8|         0.0323|\n|20 items, 4 cat, 4/16       |     0.0257|         9.8|         0.0278|\n|40 items, 4 cat, 20/20      |     0.0394|         1.2|         0.0397|\n|20 items, 2 cat, 10/10      |     0.0137|        22.0|         0.0152|\n|20 items, 4 cat, off target |     0.0177|        21.2|         0.0218|\n\n\n:::\n:::\n\n\nDropping extremes moves the size by two or three thousandths. The finding is not\nan artifact of the person estimator's behaviour at the boundary.\n\n## What this changes about the protocol {#sec-tt-implications}\n\nThe protocol's decision rule compares an observed proportion against 5%. That\nbenchmark is too lenient by a factor of 1.3 to 3.7 across everything tried here,\nworst on dichotomous items and off-target samples, which are common in health\nmeasurement. The direction is uniform, so the protocol is biased toward\ndeclaring unidimensionality.\n\nThis also gives a mechanism for Hagell's central finding [@hagell2014]. Comparing against\na benchmark that is too lenient shifts the whole power curve toward passing, so\nconclusions flipping with sample size is ordinary power behaviour against a\nbiased reference rather than a pathology of the binomial interval. With the\ncorrect reference, mild multidimensionality would be rejected at appreciably\nsmaller samples, and larger $n$ would behave the way it does in any well posed\ntest.\n\nThe constructive version is cheap. The enumeration needed to state the correct\nreference is the same machinery that produced it: one Lord-Wingersky recursion\nper subtest and one score-to-measure lookup, both of which the package already\nbuilds for `RMscoreSE()`. From that, either report the exact $\\bar\\alpha$ and\ntest the observed count against it, or replace 1.96 with the exact per-score\ncritical values so that the 5% benchmark becomes true by construction. The\nsecond is closer to what users expect the protocol to mean and needs no change\nto how results are reported.\n\n## Not yet done: the split is chosen from the data {#sec-tt-split}\n\nEverything above conditions on a fixed, known split. The protocol chooses the\nsplit by principal component analysis of residuals, taking loadings above +0.3\nand below -0.3, a cutoff whose rationale @hagell2014 already calls unclear.\nThat is a selection step, and the null conditional on a data-chosen contrast is not\nthe null for a fixed one. The enumeration therefore understates the size of the\nprotocol as practised.\n\nThe two errors run in opposite directions. Referring to 1.96, together with the\nrespondents who cannot be flagged at all, pushes the realised proportion below\n5% and makes the protocol too lenient. Selecting the most discrepant contrast\npushes it up and makes the protocol too strict. Which dominates depends on item\ncount, response categories, targeting and how unbalanced the split is, and\nnothing here settles it.\n\nSettling it needs a parametric bootstrap of the whole pipeline: generate under\nthe fitted unidimensional model, run the PCA, take the split, run the t-tests,\ncount. That is the same shape as `RMdimResidualPCACutoff()` and the infit and Q3\ncutoff work, and the exact component above would serve as its reference, which\nremoves most of the noise from the comparison the way the exact RCI null did for\nthe change study.\n\nIt is worth holding open that the two errors partly cancel. Existing simulation\nwork reporting the protocol as well behaved under unidimensionality would be\nconsistent with that, and a cancellation would not be stable across the\nconditions in the first table. I have not checked what @smith2002 or @horton2010 report on this point, so that reading is a conjecture to verify\nagainst the sources rather than a finding of this note.\n\n## Scope and limits {#sec-tt-scope}\n\n* **Complete data only**, as in the RCI chapter (@sec-rci-scope). Missing responses break\n  sufficiency of a single subtest score, so the enumeration would run per\n  missingness pattern.\n* **Fixed split.** See @sec-tt-split.\n* **WLE with CML-style thresholds.** RUMM2030's person estimator may differ. It\n  would move the centering column more than the size column, since dropping\n  extremes barely changed the latter.\n* **The latent density enters only through the weighting.** The per-score sizes\n  are free of it. Only the sample means and the count distributions depend on\n  the assumed $N(\\mu, \\sigma)$.\n* The 1.96 figure is taken as the rule in force. Software referring to a $t$\n  distribution with finite degrees of freedom uses a slightly larger value,\n  which makes the test more conservative, not less.\n\n## Reproduction {#sec-tt-reproduction}\n\n`scripts/ttest/ttest_protocol_exact_null.R` runs everything here plus the Monte Carlo\nanchor, which is not rendered. The enumeration is self-contained in the\n`exact-fns` chunk above and needs only `easyRasch2:::.pcm_cat_probs()`,\n`:::.theta_wle()` and `:::.score_pattern()`, the same three internals the RCI\nchapter uses.\n\n## Revision history {.unnumbered}\n\n- 2026-10-04: first version in this book, moved from `easyRasch2/dev/ttest_protocol_exact_null.qmd`.\n",
    "supporting": [
      "ttest-protocol-exact-null_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}