{
  "hash": "dae82563306c6c795296bfaa1b5fc0ba",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"An exact null for the Rasch change index\"\nsubtitle: \"Why the RCI critical value is not 1.96, and how to compute it without simulating\"\nauthor: \"Magnus Johansson\"\ndate: 2026-10-04\ndate-modified: 2026-10-04\n---\n\n\n\n::: {.callout-note appearance=\"simple\" icon=false}\n## About this chapter\n\n**Status:** complete<br>\n**Computed with:** easyRasch2 1.3.1.9002, R 4.6.1<br>\n**Slides:** [An exact null for two Rasch protocols](../slides/rasch-exact-null.html){target=\"_blank\"}<br>\n**Cite as:** Johansson, M. (2026). An exact null for the Rasch change index. In\n*Rasch Measurement Explorations*.\n<https://pgmj.github.io/rasch_book/chapters/rci-exact-null.html>\n:::\n\n::: {.callout-tip appearance=\"simple\" icon=false}\n## Summary\n\nThe Rasch change index (RCI) is usually referred to a standard normal\ndistribution, with 1.96 as the critical value. Under the null the RCI is not\nstandard normal, and the correct critical value is lower, about 1.7 on a\nsix-item scale and still about 1.93 at 60 items. For complete data the null\ndistribution can be computed exactly from the item parameters, without\nsimulation. The critical value depends on targeting as well as the items, so it\nshould be recalibrated on each sample rather than reused. Carry-over between\noccasions makes the test conservative and creates a spurious severity gradient\nin estimated change, and it can be detected with a Q3 screen of the racked\ndata.\n:::\n\n## Purpose {#sec-rci-purpose}\n\n`RMpersonChange()` includes an option for `critical = \"simulate\"` rather than the conventional\n1.96, because the Rasch change index\n\n$$RCI = \\frac{\\hat\\theta_2 - \\hat\\theta_1}{\\sqrt{SE(\\hat\\theta_1)^2 + SE(\\hat\\theta_2)^2}}$$\n\nis not standard normal under the null. The departure is largest on short\nscales and fades only slowly, so that even at 60 items with four response\ncategories the critical value is still around 1.93. This note shows\nthat the null does not need simulating at all: for complete data it can be\nenumerated exactly. It also records what the exact critical value does across\ntest length, sample skew and targeting, and one consequence for the RCI as a\nstatistic.\n\n## Why the null is not N(0, 1) {#sec-rci-mechanisms}\n\nTwo mechanisms, both weakening as test information grows.\n\n**Self-normalisation.** $SE(\\hat\\theta_1)$ and $SE(\\hat\\theta_2)$ are\ndeterministic functions of the realised scores, so the denominator is not\nindependent of the numerator. A respondent who moves to an extreme score\nproduces a large numerator and a large denominator together, and the ratio is\ndamped. Both tails of the null are pulled in, so the critical value falls\n**below** 1.96. In a t-test the denominator is independent of the numerator.\nHere it is not, which is why the t reference does not help either.\n\n**Discreteness.** With complete data the sum score is sufficient, so\n$\\hat\\theta$ takes only as many values as there are scores and the null is\ndiscrete rather than continuous.\n\n## Exact enumeration {#sec-rci-enumeration}\n\nSufficiency is what makes this tractable. $\\hat\\theta(r)$ and $SE(r)$ are\ndeterministic lookups, the ones `RMscoreSE()` builds, and $P(r \\mid \\theta)$\nfollows from the Lord-Wingersky recursion. Under the null the two occasions are\nindependent given $\\theta$, so the joint is $P(r_1 \\mid \\theta)P(r_2 \\mid\n\\theta)$ and the whole null is a discrete distribution over $(k+1)^2$ score\npairs. For six items with four response categories that is 361 cells.\n\nThe two ingredients do different jobs and the enumeration needs both.\nSufficiency fixes the **value** of the statistic in every cell, because\n$\\hat\\theta$ and $SE$ are functions of the score alone, and no probability\nenters that map. A quantile also needs the **weight** on each cell, which is\n$P(r \\mid \\theta)$, and that is not deterministic. Lord-Wingersky computes it\nrather than estimating it: the recursion is the elementary symmetric function\nidentity in probability form, the same object CML estimation runs on, and it\nreplaces an enumeration over $\\prod_i (m_i + 1)$ response patterns, 4096 here\nand around $10^{12}$ at twenty items. Nothing in this note is simulated, which\nis what \"exact\" refers to. Nor is there a closed-form expression for the\ncritical value. It is read off the enumerated distribution as a quantile.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# One threshold constructor for the whole note: k items, ncat response\n# categories, item locations spread over [-1.2, 1.2].\nmk <- function(k, ncat) {\n  lapply(seq(-1.2, 1.2, length.out = k),\n         function(b) b + seq(-0.9, 0.9, length.out = ncat - 1L))\n}\n\n# Lord-Wingersky: exact sum-score distribution given theta under a PCM\nscore_dist <- function(thr_list, theta) {\n  d <- 1\n  for (thr in thr_list) {\n    p <- easyRasch2:::.pcm_cat_probs(theta, thr)\n    nd <- numeric(length(d) + length(p) - 1L)\n    for (a in seq_along(d)) {\n      nd[a + seq_along(p) - 1L] <- nd[a + seq_along(p) - 1L] + d[a] * p\n    }\n    d <- nd\n  }\n  d                                   # index is score + 1\n}\n\n# Exact null distribution of the RCI, pooled over a set of person locations\nexact_crit <- function(thr_list, thetas, alpha = 0.05) {\n  steps <- vapply(thr_list, length, integer(1L))\n  lut <- vapply(0:sum(steps), function(r) {\n    easyRasch2:::.theta_wle(\n      easyRasch2:::.score_pattern(r, steps), thr_list, c(-10, 10)\n    )\n  }, numeric(2L))\n  th <- lut[1L, ]\n  se <- lut[2L, ]\n  rci <- outer(seq_along(th), seq_along(th),\n               function(i, j) (th[j] - th[i]) / sqrt(se[i]^2 + se[j]^2))\n  w <- matrix(0, length(th), length(th))\n  for (t in thetas) {\n    d <- score_dist(thr_list, t)\n    w <- w + outer(d, d)\n  }\n  w <- w / sum(w)\n  o <- order(as.numeric(rci))\n  v <- as.numeric(rci)[o]\n  cw <- cumsum(as.numeric(w)[o])\n  c(lower = v[which(cw >= alpha / 2)[1L]],\n    upper = v[which(cw >= 1 - alpha / 2)[1L]])\n}\n```\n:::\n\n\n## Validation against simulation {#sec-rci-validation}\n\nRun by `dev/` scratch scripts at `sim_iter` 2000 to 4000, n = 200, alpha = .05\ntwo-sided. The simulated and exact values agree to within Monte Carlo error in\nevery configuration tried, including dichotomous items, items with unequal\ncategory counts, a right-skewed person distribution and a badly off-target one.\nEach configuration was run on its own simulated sample, so the values are not\ncomparable with the length table below, which uses a different person\ndistribution. The 12-item row sitting near the 20-item value there is an\ninstance of that, not a property of test length.\n\n| configuration | simulated | exact | difference |\n|---|---|---|---|\n| 6 items, 4 categories, symmetric theta | −1.695 / +1.695 | ±1.695 | 0.000 |\n| 6 items, 4 categories, skewed theta | −1.725 / +1.695 | ±1.695 | 0.030 |\n| 6 items, 4 categories, skewed and off target | −1.534 / +1.534 | ±1.522 | 0.012 |\n| 20 items, 2 categories, symmetric | −1.798 / +1.798 | ±1.798 | 0.000 |\n| 20 items, 2 categories, skewed | −1.798 / +1.798 | ±1.798 | 0.000 |\n| 9 items, mixed 2/3/4 categories, symmetric | −1.721 / +1.721 | ±1.721 | 0.000 |\n| 9 items, mixed 2/3/4 categories, skewed | −1.721 / +1.721 | ±1.721 | 0.000 |\n| 12 items, 4 categories, symmetric | −1.864 / +1.864 | ±1.862 | 0.002 |\n\nThe exact values are perfectly symmetric. That is the expected result: under the\nnull the two occasions are exchangeable, so $\\hat\\theta_2 - \\hat\\theta_1$ is\nsymmetric about zero however skewed $\\hat\\theta$ itself is. The residual\nasymmetry in the simulated column is Monte Carlo noise. Asymmetry becomes real\nonly when exchangeability fails, which in practice means the two occasions\ndiffering in which items were answered.\n\n## The critical value tracks test information {#sec-rci-length}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1)\ntheta <- rnorm(400, 0, 1.4)\ntab <- t(vapply(c(4, 6, 10, 20, 40), function(k) {\n  c(items = k, exact_crit(mk(k, 4), theta)[[\"upper\"]])\n}, numeric(2L)))\nkable(tab, digits = 3, col.names = c(\"Items\", \"Critical value\"))\n```\n\n::: {.cell-output-display}\n\n\n| Items| Critical value|\n|-----:|--------------:|\n|     4|          1.644|\n|     6|          1.725|\n|    10|          1.815|\n|    20|          1.868|\n|    40|          1.915|\n\n\n:::\n:::\n\n\nPerson locations are a sample of 400 from $N(0, 1.4)$, and the number of\nresponse categories is held at four throughout. The critical value is monotone\nin test length, converging on 1.96. Referring the RCI to a normal null is\ntherefore conservative, and increasingly so the shorter the scale. At six items\nand four categories, using 1.96 instead of 1.725 is a materially stricter test.\n\nThe convergence is slow. Extending the same setup, integrated over $N(0, 1.4)$\nby quadrature rather than sampled, the value is 1.933 at 60 items, 1.949 at 200\nand 1.956 at 600, and does not reach 1.96 in that range. It is within 0.03 of\n1.96 from about 60 items, where the size of a 1.96 test is roughly .047 and the\ndifference no longer matters. Dichotomous items converge more slowly and not\nmonotonically, because of discreteness: 1.734 at 10 items, 1.720 at 20, 1.926\nat 100 and 1.953 at 600. Computed in `scripts/rci/rci_crit_by_length.R`.\n\nResponse categories have to be reported alongside item count, because a\nsix-item scale with three categories and one with seven are not comparable\ninstruments. They do not act on the two quantities in the same way:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncats <- t(vapply(c(2, 3, 4, 5, 7), function(nc) {\n  thr <- mk(6, nc)\n  names(thr) <- paste0(\"I\", seq_along(thr))\n  d <- as.data.frame(easyRasch2:::sim_partial_score(thr, theta))\n  colnames(d) <- names(thr)\n  rel <- RMreliabilityCurve(d, item_params = thr, output = \"dataframe\")\n  c(categories = nc,\n    critical = exact_crit(thr, theta)[[\"upper\"]],\n    marginal = attr(rel, \"marginal_ratio\"))\n}, numeric(3L)))\nkable(cats, digits = 3,\n      col.names = c(\"Categories\", \"Critical value\", \"Marginal reliability\"))\n```\n\n::: {.cell-output-display}\n\n\n| Categories| Critical value| Marginal reliability|\n|----------:|--------------:|--------------------:|\n|          2|          1.546|                0.615|\n|          3|          1.724|                0.764|\n|          4|          1.725|                0.829|\n|          5|          1.727|                0.872|\n|          7|          1.779|                0.906|\n\n\n:::\n:::\n\n\nReliability climbs steeply with categories, from about .60 at two to about .91\nat seven. The critical value does not follow it. Almost all of its movement is\nthe step from dichotomous to polytomous, after which it is close to flat. So\ncategories add precision without much changing how far the null lies from\n1.96, while items move both. Reliability and conditional reliability are discussed further in @sec-rci-reliability.\n\n## Skew and targeting {#sec-rci-targeting}\n\nSample skew on its own barely moves the pooled critical value: the skewed and\nsymmetric rows above agree to the third decimal in five of seven configurations.\nTargeting is what matters. Pushing the same skewed distribution 2.2 logits off\ntarget, so that 39.5% of respondents are at an extreme score at one occasion or\nthe other, drops the critical value from 1.695 to 1.522. The mechanism is the\nself-normalisation in @sec-rci-mechanisms: a floor-bound sample is located primarily where the\nstatistic is most heavily damped.\n\nThis also means the pooled critical value is a property of the sample as well as\nthe items, which is worth stating wherever it is reported.\n\nRecalibrating on each sample, which is what the function does, keeps the test\nclose to its nominal level even when targeting is poor. **Carrying a critical\nvalue across samples does not.** Applying a value calibrated on a well-targeted\nsample to one sitting two logits off target gave a realised size of .028 against\na nominal .05 on six items, where recalibrating on that sample held .042. Quote\nthe value with the sample it came from, and recalibrate rather than reusing a\npublished figure.\n\n## Can the sample dependence be removed? {#sec-rci-conditional}\n\nConditioning on the total score is what removed the latent distribution from the\nsubtest problem of the PCA/t-test chapter (@sec-tt-conditioning), and the same argument applies here. Under\nthe null the two occasions are independent given $\\theta$ and use the same\nitems, so\n\n$$P(r_1 = a \\mid r_1 + r_2 = s) = \\frac{\\gamma(a)\\,\\gamma(s-a)}{\\gamma_2(s)}$$\n\nwhere $\\gamma_2$ is the elementary symmetric function of the item set counted\ntwice. The ratio is free of $\\theta$, verified to between 2.2e-16 and 3.9e-16\nacross four configurations including dichotomous and mixed-category scales. A\nper-respondent null is therefore available with no latent density and no plug-in\nperson estimate.\n\nIt is not worth using. Conditioning on the total leaves few attainable pairs, so\nthe discrete test falls short of its nominal level. Mean achievable size at\n$\\alpha = .05$, weighted by the two-occasion score distribution of an $N(0, 1)$\nsample:\n\n| Scale | strict p | mid-p | cannot reject (%) |\n|---|---|---|---|\n| 6 items, 4 cat | 0.0174 | 0.0493 | 1.4 |\n| 12 items, 4 cat | 0.0260 | 0.0524 | 0.2 |\n| 20 items, 4 cat | 0.0312 | 0.0526 | 0.0 |\n| 20 items, 2 cat | 0.0261 | 0.0341 | 1.2 |\n| 40 items, 4 cat | 0.0335 | 0.0482 | 0.0 |\n\nA mid-p correction recovers the level, overshooting slightly on the middle\nscales. The degeneracy is minor: respondents whose total admits no rejection\nwhatever are at most 1.4 percent of an on-target sample, because extreme totals\nare rare.\n\nWhat settles it is that neither version improves on what the function already\ndoes. The case with no sample to pool over, and the one this construction was\nmeant to serve, is a single respondent measured against external item\nparameters. Exact size given that respondent's true location, six items with\nfour categories:\n\n| true $\\theta$ | plug-in | strict | mid-p |\n|---|---|---|---|\n| -3 | .0195 | .0080 | .0265 |\n| -2 | .0492 | .0196 | .0355 |\n| -1 | .0473 | .0163 | .0489 |\n| 0 | .0428 | .0184 | .0540 |\n| +2 | .0492 | .0196 | .0355 |\n| +3 | .0195 | .0080 | .0265 |\n\nThe plug-in holds between .043 and .051 through the middle of the scale and\nturns conservative only in the tails, where the scale runs out of scores. Exact\npower at a true location of zero on twenty items tells the same story: at a\nchange of one logit it is .618 for the plug-in, .626 for mid-p and .537 for\nstrict, and mid-p's small edge tracks its slightly larger size rather than any\nreal gain.\n\nThe negative result is worth recording because it accounts for something this\nnote otherwise reports without explanation. The conditional null given the total\ndoes not depend on $\\theta$ at all, so an error in a plug-in $\\hat\\theta$\nreaches the critical value only through the weighting. That is why\n`conditional_crit = TRUE` performs as well as it does from a single respondent's\nown two estimates, and why the pooled default survives poor targeting once it is\nrecalibrated. The default is unchanged. Worked out in\n`scripts/rci/conditional_total_null.R`.\n\n## A consequence for the RCI as a statistic {#sec-rci-ordering}\n\nBecause the denominator is a function of the same scores as the numerator, the\nRCI does not order respondents by how much they changed. A concrete pair from\nthe six-item scale above:\n\n| | score change | change in logits | RCI |\n|---|---|---|---|\n| A | 0 → 18 | 7.24 | 3.53 |\n| B | 3 → 15 | 3.11 | 3.60 |\n\nRespondent A moved the full width of the scale, 4.14 logits further than B, and\nscores lower on the RCI. Both are far past any critical value so nothing turns\non it here, but it shows that the RCI is a standardised distance from the null\nrather than a measure of change, and should not be read as the latter.\n\nThe constructive version: since the critical value has to be computed from the\nitem parameters anyway, the normalisation adds nothing that a location-specific\nthreshold on the raw change would not. The same enumeration gives the null of\n$\\hat\\theta_2 - \\hat\\theta_1$ directly, so a conditional critical **change**, in\nlogits, is available at no extra cost and is monotone in what happened. That is\nthe same object as a conditional minimal detectable change, and connects to the\nscore-level MDC table parked as a possible sibling function.\n\n## The no-change band in the figure {#sec-rci-band}\n\nThe scatter plot of occasion 1 against occasion 2 draws a band covering the\nchanges that would not be flagged. That band was built from a smooth\napproximation, half-width $c \\cdot \\sqrt{2/I(\\theta)}$, which places **both**\noccasions at the baseline location. The test does not do that. It uses\n$SE(r_1)$ and $SE(r_2)$ at two different scores.\n\nOn 300 respondents the two disagreed for 33 of them, 11 percent: 27 sat outside\nthe drawn band without being flagged, and 6 sat inside it while flagged. The\nfigure contradicted the table it accompanied.\n\nThe mechanism shows in the worst case. A respondent moving from $\\theta_1 =\n1.23$ to $\\theta_2 = 3.62$ had a band built on $SE_{diff} = 0.79$, because\ninformation is high at 1.23, while the test used 1.56, because the follow-up\nscore is at the ceiling. The band was about half the width it should have\nbeen, in precisely the case the figure exists to display: a large change landing\nnear a boundary.\n\nThe band is now built from the same lookup the test uses. For each attainable\nbaseline score, the follow-up locations that would not be flagged are read off\ndirectly, so a point lies outside the band if and only if that respondent was\nflagged. Verified at zero disagreements out of 300 and pinned by a regression\ntest. Because attainable scores are discrete the band is a step function, which\nalso makes the discreteness visible rather than hiding it behind a smooth curve.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1)\nthr_demo <- mk(6, 4)\nnames(thr_demo) <- paste0(\"I\", seq_along(thr_demo))\n\ntheta_demo <- rnorm(300, 0, 1.6)\nt1 <- as.data.frame(easyRasch2:::sim_partial_score(thr_demo, theta_demo))\nt2 <- as.data.frame(easyRasch2:::sim_partial_score(thr_demo, theta_demo + 0.7))\ncolnames(t1) <- colnames(t2) <- names(thr_demo)\n\n# Item parameters are estimated from the data here, as a reader would, so that\n# this figure and the reliability output below share one calibration.\nRMpersonChange(t1, t2, critical = \"exact\", output = \"ggplot\")\n```\n\n::: {.cell-output-display}\n![Default `RMpersonChange()` figure. Three hundred respondents on a scale of six items with four response categories, generated with a true shift of 0.7 logits between occasions. The grey band covers the follow-up locations that would not be flagged from each baseline score, so a point lies outside it if and only if that respondent was flagged. Its steps are the attainable scores, and it is widest away from the centre.](rci-exact-null_files/figure-html/fig-rci-change-1.png){#fig-rci-change fig-alt='Scatter plot of person location at occasion 1 against occasion 2, both in logits from about -4 to 4. Points fall on a discrete grid because attainable scores are discrete. A grey stepped band runs along the diagonal, narrow near the centre of the scale and wider towards each end before narrowing again at the extremes. Points inside the band are grey and labelled as no detected change, points above it are green and labelled as an increase, and one point below it is orange and labelled as a decrease. Most points sit above the diagonal, reflecting the simulated improvement.'}\n:::\n:::\n\n\nThe band table below gives the same object numerically.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nthr6 <- mk(6, 4)\ncrit <- exact_crit(thr6, theta)\n\nband_rows <- function(thr_list, lo, hi) {\n  steps <- vapply(thr_list, length, integer(1L))\n  lut <- vapply(0:sum(steps), function(r) {\n    easyRasch2:::.theta_wle(\n      easyRasch2:::.score_pattern(r, steps), thr_list, c(-10, 10)\n    )\n  }, numeric(2L))\n  th <- lut[1L, ]\n  se <- lut[2L, ]\n  do.call(rbind, lapply(seq_along(th), function(i) {\n    rci <- (th - th[i]) / sqrt(se[i]^2 + se^2)\n    keep <- rci <= hi & rci >= lo\n    data.frame(baseline = th[i], lower = min(th[keep]), upper = max(th[keep]))\n  }))\n}\n\nb <- band_rows(thr6, crit[[\"lower\"]], crit[[\"upper\"]])\nb$width <- b$upper - b$lower\nkable(b, digits = 2, row.names = FALSE,\n      col.names = c(\"Baseline theta\", \"Lower\", \"Upper\", \"Width\"))\n```\n\n::: {.cell-output-display}\n\n\n| Baseline theta| Lower| Upper| Width|\n|--------------:|-----:|-----:|-----:|\n|          -3.73| -3.73| -1.27|  2.46|\n|          -2.58| -3.73| -0.98|  2.74|\n|          -2.01| -3.73| -0.72|  3.01|\n|          -1.60| -3.73| -0.47|  3.25|\n|          -1.27| -3.73|  0.00|  3.73|\n|          -0.98| -2.58|  0.23|  2.82|\n|          -0.72| -2.01|  0.47|  2.48|\n|          -0.47| -1.60|  0.72|  2.32|\n|          -0.23| -1.27|  0.98|  2.26|\n|           0.00| -1.27|  1.27|  2.55|\n|           0.23| -0.98|  1.60|  2.59|\n|           0.47| -0.72|  1.60|  2.32|\n|           0.72| -0.47|  2.01|  2.48|\n|           0.98| -0.23|  2.58|  2.82|\n|           1.27|  0.00|  3.73|  3.73|\n|           1.60|  0.23|  3.73|  3.49|\n|           2.01|  0.72|  3.73|  3.01|\n|           2.58|  0.98|  3.73|  2.74|\n|           3.73|  1.27|  3.73|  2.46|\n\n\n:::\n:::\n\n\nThe width is not monotone in distance from the centre, which is worth knowing\nbefore reading a figure. It peaks off centre, where the standard error is\nalready large but the scale has not run out of room, and narrows again at the\nboundary itself because there are no further attainable scores to move to. For\nthis scale, six items with four categories, the widest band is 3.62 logits at a\nbaseline near $\\pm 1.2$, against 2.47 at the centre and 2.39 at the extremes.\n\nTwo cases remain indicative rather than exact, and are documented as such: with\nmixed missingness the band is drawn for the most common pair of answered-item\nsets, and under `conditional_crit = TRUE` it uses the median critical values.\n\n## What the change figure is resting on {#sec-rci-reliability}\n\nA change verdict is only as good as the precision behind it, and the reader of\nthe figure above has no way to judge that from the figure alone. The same scale,\nsix items with four response categories, summarised the two ways the package\noffers.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nRMreliability(t1, draws = 200, rmu_iter = 10, seed = 1, boot = TRUE)\n```\n\n::: {.cell-output-display}\n\n\nTable: Reliability for 6 items, n = 300 respondents. PSI is the WLE-based separation reliability and excludes min/max scoring respondents. Marginal is the latent-density-weighted mean of the conditional reliability curve, sigma^2 / (sigma^2 + SEM(theta)^2).\n\n|Metric                | Estimate| Lower (95% HDCI)| Upper (95% HDCI)|Notes                      |\n|:---------------------|--------:|----------------:|----------------:|:--------------------------|\n|Cronbach's alpha      |    0.868|            0.850|            0.889|200 bootstrap resamples    |\n|PSI                   |    0.796|            0.772|            0.820|200 bootstrap resamples    |\n|Marginal (curve mean) |    0.856|            0.843|            0.870|200 bootstrap resamples    |\n|RMU (WLE)             |    0.861|            0.839|            0.882|200 PVs, 10 RMU iterations |\n\n\n:::\n:::\n\n\nMarginal reliability near .85 is respectable for six items with four response\ncategories, and the gap down to PSI is the ordinary one between a model-based\ncoefficient integrated over the fitted latent density and a sample-based one\ncomputed from the observed spread of the estimates.\n\nThe \"Marginal (curve mean)\" row and the dashed line in the curve below are the\nsame number, the latent-density-weighted mean of the conditional reliability\ncurve. `RMreliabilityCurve()` returns it as the `marginal_ratio` attribute, and\nthe two agree to machine precision whenever both are given the same data and the\nsame calibration.\n\nA single coefficient hides where that precision lies, which is the same point\nthe stepped band makes in the change figure.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nRMreliabilityCurve(t1, statistic = \"reliability\", benchmark = 0.8)\n```\n\n::: {.cell-output-display}\n![Conditional reliability across the scale for the same six items with four response categories, with the region reaching .8 shaded and the respondent distribution behind it.](rci-exact-null_files/figure-html/fig-rci-relcurve-1.png){#fig-rci-relcurve fig-alt='Conditional reliability plotted against person location in logits. The curve is an inverted U, peaking a little above 0.85 near the centre of the scale and falling below 0.5 at both extremes. A shaded vertical band marks the region where reliability reaches 0.8, covering roughly the middle two thirds of the plotted range. A grey distribution along the bottom shows where respondents fall, concentrated near the centre.'}\n:::\n:::\n\n\nRead @fig-rci-change and @fig-rci-relcurve together. Where this curve is high the band in the change\nfigure is narrow and a modest change is detectable. Where it falls away the band\nwidens and only a large change clears it. The band narrowing again at the very\nextremes is not precision returning, it is the scale running out of scores.\n\n## Response dependence between occasions {#sec-rci-carryover}\n\nEverything above assumes the two occasions are independent given $\\theta$. That\nis a conditional statement, and it is compatible with the two estimates being\nstrongly correlated marginally, which they are. Both measure the same person,\nand that shared $\\theta$ is what makes their difference interpretable. The\nassumption concerns what is left once $\\theta$ is accounted for.\n\nWhat it rules out is carry-over: a time-2 answer depending on the time-1 answer\nto the same item beyond what $\\theta$ explains. Administering the occasions\nseparately does not deliver conditional independence on its own.\n@marais2009 models the failure by shifting the time-2 difficulty of item $j$ by\n$(1 - 2x_{j1})d$, so a positive response at time 1 makes that item easier at\ntime 2 and a negative one makes it harder. @marais2008a separate this\n**response dependence** from **trait dependence**, which is multidimensionality.\nOnly the second is a failure of unidimensionality, and the two call for\ndifferent remedies.\n\nThis matters here in a way it does not for the PCA/t-test protocol\n(@sec-tt-statistic). There, conditional independence between the two item subsets is the\nnull hypothesis, so a failure of it is what the test exists to detect. Here it\nis an auxiliary assumption: the null is that $\\theta$ did not change, and\ncarry-over can be present while $\\theta$ is fixed.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Marais's model, generalised to polytomous items by shifting every threshold\n# of item j by (1 - 2 * x_j1 / m_j) * d, which reduces to her dichotomous form\n# when m_j = 1. Shifting all thresholds by s is the same as shifting theta by\n# -s, so the shift is applied as an effective theta.\nrpcm <- function(theta_eff, thr) {\n  m <- length(thr)\n  num <- matrix(0, length(theta_eff), m + 1L); cs <- cumsum(thr)\n  for (k in seq_len(m)) num[, k + 1L] <- k * theta_eff - cs[k]\n  num <- exp(num - apply(num, 1L, max))\n  cp <- t(apply(num / rowSums(num), 1L, cumsum))\n  max.col(cp >= runif(length(theta_eff)), ties.method = \"first\") - 1L\n}\n\nsim_pair <- function(thr_list, theta1, theta2, d = 0) {\n  k <- length(thr_list); n <- length(theta1)\n  mj <- vapply(thr_list, length, integer(1L))\n  x1 <- vapply(seq_len(k), function(j) rpcm(theta1, thr_list[[j]]), integer(n))\n  sh <- if (d == 0) matrix(0, n, k) else (1 - 2 * sweep(x1, 2L, mj, \"/\")) * d\n  x2 <- vapply(seq_len(k), function(j)\n          rpcm(theta2 - sh[, j], thr_list[[j]]), integer(n))\n  list(t1 = x1, t2 = x2)\n}\n\n# Wider item spread than mk() above, following Marais's [-2.5, 2.5]\nmk_wide <- function(k, ncat) {\n  lapply(seq(-2.5, 2.5, length.out = k),\n         function(b) b + seq(-0.9, 0.9, length.out = ncat - 1L))\n}\n\nscore_lut <- function(thr_list) {\n  steps <- vapply(thr_list, length, integer(1L))\n  vapply(0:sum(steps), function(r)\n    easyRasch2:::.theta_wle(easyRasch2:::.score_pattern(r, steps),\n                            thr_list, c(-10, 10)), numeric(2L))[1L, ]\n}\n```\n:::\n\n\nThe mechanism is easiest to see with no true change at all. Holding every\nrespondent at one location and generating both occasions from it, the mean\nobserved change should be zero at every location, and is when $d = 0$. Twenty\nitems, four categories, item locations over [-2.5, 2.5], 4000 respondents per\ncell, change in logits.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(808)\nthr_d <- mk_wide(20, 4); th_lut <- score_lut(thr_d)\ngrid_t <- seq(-2.5, 2.5, by = 0.5)\ndrift <- sapply(c(0, 0.5, 1, 1.5), function(d)\n  sapply(grid_t, function(t0) {\n    p <- sim_pair(thr_d, rep(t0, 4000), rep(t0, 4000), d = d)\n    mean(th_lut[rowSums(p$t2) + 1L] - th_lut[rowSums(p$t1) + 1L])\n  }))\ndimnames(drift) <- list(sprintf(\"%.1f\", grid_t),\n                        paste0(\"d = \", c(0, 0.5, 1, 1.5)))\nkable(drift, digits = 3)\n```\n\n::: {.cell-output-display}\n\n\n|     |  d = 0| d = 0.5|  d = 1| d = 1.5|\n|:----|------:|-------:|------:|-------:|\n|-2.5 | -0.007|  -0.210| -0.359|  -0.465|\n|-2.0 | -0.007|  -0.136| -0.227|  -0.294|\n|-1.5 |  0.000|  -0.080| -0.136|  -0.179|\n|-1.0 |  0.002|  -0.048| -0.079|  -0.100|\n|-0.5 |  0.001|  -0.020| -0.037|  -0.045|\n|0.0  |  0.005|  -0.002| -0.017|   0.003|\n|0.5  |  0.003|   0.026|  0.043|   0.047|\n|1.0  |  0.004|   0.047|  0.080|   0.106|\n|1.5  | -0.004|   0.097|  0.148|   0.185|\n|2.0  |  0.001|   0.137|  0.231|   0.293|\n|2.5  |  0.000|   0.200|  0.361|   0.459|\n\n\n:::\n:::\n\n\nCarry-over produces an antisymmetric **outward drift**: zero at the item mean,\npushing respondents further out the further out they already are, and reaching\nalmost half a logit at the ends by $d = 1.5$. This is the individual-level\nmechanism behind the group-level result Marais reports [@marais2009], where easy items\nput the sample above the item mean, everyone drifts up, and a group mean shows\nchange that did not happen.\n\n### What it does to the test\n\nThe remaining results come from `scripts/rci/carryover_dependence.R`, which is not run\nat render time. That script also validates the generator against Marais's\npublished Table 4, reproducing her mean same-item residual correlations of\n-0.01, 0.14, 0.31 and 0.47 as -0.02, 0.13, 0.28 and 0.44.\n\nWith no true change, and critical values calibrated under independence as this\nnote recommends, the test becomes conservative rather than liberal. The\nstandard deviation of the RCI falls from about 0.97 to between 0.63 and 0.73,\nso the exact critical values are too wide for the null actually in force.\nType I error against a nominal .05, on-target sample:\n\n| Scale | d = 0 | d = 0.5 | d = 1 | d = 1.5 |\n|---|---|---|---|---|\n| 20 items, 4 cat | .0487 | .0267 | .0133 | .0074 |\n| 6 items, 4 cat | .0509 | .0261 | .0121 | .0056 |\n| 25 items, 2 cat | .0488 | .0262 | .0103 | .0032 |\n\nThe direction of the false positives is the part that does damage. At $d = 0$\nthey split evenly, as they must. As dependence grows they polarise, because the\ndrift carries each respondent away from the item mean and the sign of that\nmovement is fixed by where the respondent already was. Twenty items with four\ncategories, on target:\n\n| d | share \"increase\" among those above the items | share \"decrease\" among those below |\n|---|---|---|\n| 0 | 0.51 | 0.49 |\n| 0.5 | 0.75 | 0.75 |\n| 1.0 | 0.88 | 0.89 |\n| 1.5 | 0.97 | 1.00 |\n\nWith a real change the same drift manufactures a severity gradient. Simulating\na uniform improvement of 0.5 logits for every respondent on twenty items with\nfour categories, the estimated change in logits comes out as:\n\n| d | overall | below items | near items | above items | above - below |\n|---|---|---|---|---|---|\n| 0 | 0.498 | 0.497 | 0.498 | 0.496 | -0.001 |\n| 0.5 | 0.436 | 0.349 | 0.431 | 0.544 | 0.195 |\n| 1.0 | 0.374 | 0.225 | 0.368 | 0.551 | 0.326 |\n| 1.5 | 0.324 | 0.138 | 0.316 | 0.547 | 0.409 |\n\nA flat treatment effect reads as a 0.41 logit gradient in baseline severity, and\na reader with no access to $d$ has no way to tell that apart from a real\ninteraction between treatment and baseline. Power falls at the same time, from\n.189 to .043 on twenty items and from .083 to .013 on six.\n\n### Why `null = \"retest\"` does not help\n\n`retest_sd` adds an independent occasion deviation at each administration. That\nis symmetric extra variance, and it widens an already conservative null. The\ndrift above is an antisymmetric shift in the conditional mean, which extra\nvariance does not touch. The two estimands in `RMpersonChange()` are both\ndefined under conditional independence, so neither covers this.\n\n### Detecting it\n\nRacking the two occasions into one analysis of $2k$ items and screening the\nsame-item pairs against `RMlocdepQ3Cutoff()` finds it well below the level that\ndoes damage. Twenty items, four categories, $n = 500$:\n\n| d | pairs flagged of 20 | runs flagging any |\n|---|---|---|\n| 0 | 0.0 | 0% |\n| 0.5 | 3.3 | 100% |\n| 1.0 | 14.2 | 100% |\n\n@marais2009 judged $d = 0.5$ likely to pass unnoticed and $d = 1$\npossibly so, working from raw residual correlations and from differential item\nfunctioning by occasion, neither of which carried a calibrated reference.\nAgainst a simulation-based cutoff the lowest level she studied is caught in all\n25 runs, with a clean zero under the null. Her conclusion about detectability\nreflects the diagnostics available at the time rather than a limit of the data.\n\nTwo details decide whether this works in practice. **The statistic has to be\ncentred on the cross-occasion pairs**, not Yen-corrected against every pair.\nSubtracting the mean of all off-diagonal $Q3$ mixes within-occasion pairs into\nthe reference and costs power: at $d = 0.5$ the two centrings detect in 96 and\n100 percent of runs respectively, and the gap widens when real change is also\npresent.\n\n**Heterogeneous true change does not masquerade as carry-over**, which was the\nobjection worth settling before recommending the screen at all. Both act on the\ncross-occasion block, so it is not obvious on paper that they separate. They do,\nbecause carry-over is item-specific and change is not:\n\n| condition | same-item | other cross-occasion | contrast | within-occasion |\n|---|---|---|---|---|\n| no change, no carry-over | -0.004 | 0.000 | -0.004 | 0.000 |\n| uniform change +0.5 | -0.004 | 0.000 | -0.004 | 0.000 |\n| change SD 0.6 | -0.039 | -0.034 | -0.005 | 0.036 |\n| carry-over d = 0.5 | 0.147 | -0.005 | 0.152 | -0.004 |\n| carry-over d = 1.0 | 0.274 | -0.008 | 0.281 | -0.007 |\n| both, d = 1 and SD 0.6 | 0.224 | -0.032 | 0.255 | 0.020 |\n\nUniform change is absorbed into the time-2 item locations and leaves no trace,\nwhich is the property Marais relies on for the rack analysis. Change that varies\nbetween respondents is a second person dimension: it lifts the within-occasion\npairs, depresses the cross-occasion block as a whole, and leaves the contrast\nflat. Carry-over lifts the same-item pairs and nothing else. When both are\npresent the two signatures add without interfering. Screened against the\nsimulated cutoff, no run out of five flagged a single pair under heterogeneous\nchange at SD 0.6 or SD 1.0, so the screen does not confuse the two.\n\n## Scope and limits {#sec-rci-scope}\n\n* **Complete data only.** Missing data breaks sufficiency of a single sum score.\n  Each distinct missingness pattern has its own score distribution and its own\n  lookup, so the enumeration still works but per pattern.\n* **`null = \"retest\"` needs quadrature.** The occasion deviations are\n  continuous, so the joint becomes a double integral over $u_1, u_2$ rather than\n  a pure sum. Still deterministic and cheap at, say, 21 nodes a side.\n* **EAP is fine.** On complete data an EAP estimate is also a function of the\n  sum score.\n* Validated here for WLE with CML thresholds. Not yet checked against MML item\n  parameters.\n* **Conditional independence between occasions is assumed, not tested.** The\n  enumeration is correct under it and says nothing about carry-over. See\n  @sec-rci-carryover, and screen for it before relying on a change verdict.\n\n## Implemented {#sec-rci-implemented}\n\nShipped as `critical = \"exact\"`, now the default in `RMpersonChange()`, in\n`R/person_change_exact.R`. Measured against a 4000-iteration simulation on the\nsame data: critical values agree to within Monte Carlo error, p-values correlate\nat 0.9998, classifications are identical, and the exact path takes 0.08 s\nagainst 13.7 s. Incomplete data is enumerated within each missingness pattern,\n`null = \"retest\"` integrates the occasion deviations out by quadrature (they are\nindependent, so the joint factorises and the retest null costs no more than the\nmeasurement null), and EAP is supported by holding the prior at the one the\nobserved respondents were scored under.\n\nHaving an exact reference immediately paid for itself twice. It exposed a bug in\nthe simulation path, which had been re-estimating the EAP prior from each null\ndataset rather than holding it at the observed one. That is now fixed, and the\ntwo paths agree to four decimals under EAP. It also supplied the lookup needed\nto fix the figure, described in @sec-rci-band.\n\nIt also removes the one real objection to `conditional_crit = TRUE`: a\nper-respondent critical value from simulation rests on `sim_iter` draws, roughly\n25 of which land in each tail at alpha = .05, whereas $P(r \\mid \\theta_i)$ is\navailable per respondent for free.\n\nIt would also improve the planned simulation study, whose first aim is the\nrealised Type I error of the simulated critical value. Much of the noise in that\ncomparison disappears if the reference is exact.\n\n## Reproduction {#sec-rci-reproduction}\n\nScratch scripts used for the simulated column are not part of the package. The\nexact computation is self-contained in the `exact-fns` chunk above and needs\nonly `easyRasch2:::.pcm_cat_probs()`, `:::.theta_wle()` and `:::.score_pattern()`.\n\n## Revision history {.unnumbered}\n\n- 2026-10-04: first version in this book, moved from `easyRasch2/dev/rci_exact_null.qmd`.\n",
    "supporting": [
      "rci-exact-null_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}